  const AXES6 = ['Transparency', 'Methodology', 'Revenue', 'Authenticity', 'Reg. Match', 'Track Record'];
  const AXIS_FULL_NAMES = ['Transparency of Operator Information', 'Disclosure of Rating Logic', 'Disclosure of Revenue Model', 'Review Authenticity Safeguards', 'Consistency with Regulatory Data', 'History of Problem Cases'];

  // ---------- Audited case data (axis order matches AXES6/AXIS_FULL_NAMES) ----------
  const SITE_DATA = {
    wikifx: {
      caseNo: 'CASE No. 001',
      name: 'WikiFX',
      siteUrl: 'https://www.wikifx.com/',
      status: 'unrecommended',
      statusLabel: 'Not Recommended',
      scores: [1, 3, 1, 2, 1, 1],
      notes: [
        "The official 'About Us' page lists no company name, address, or representative (contact details only). Hong Kong's Securities and Futures Commission (SFC) has officially warned that the Hong Kong address the company claims does not exist and that it is suspected of using a legitimate company's information without authorization.",
        "The company publishes a framework of five indicators — 'License/Regulation/Risk Control/Business/Software' — but the detailed calculation method is not disclosed, and multiple reports note that inquiries go unanswered.",
        'No disclosure of a revenue model appears anywhere on the site. Internal documents obtained by investigative outlet DL News reportedly show the company demanding up to $128,000 from brokers, with high scores for those who pay and low scores for those who refuse (the company denies this).',
        "Numerous reports describe unverified submissions being reflected directly in scores. Its Trustpilot rating is also 'Poor' at 2/5.",
        "Numerous cases have been reported of properly licensed brokers regulated by the FCA, CySEC, and others being mislabeled as 'unregistered' or 'suspicious.' In addition, the company's own registered address has been identified by Hong Kong's SFC as nonexistent.",
        "Multiple independent sources corroborate this: DL News's investigative reporting, Hong Kong SFC's official warning, reporting of similar allegations against sister site WikiBit, and public accusations from multiple brokers.",
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Finance Magnates — Hong Kong SFC warns of WikiFX', url: 'https://www.financemagnates.com/forex/hong-kong-continues-to-scrutinize-fx-space-warns-of-wikifx/' },
        { label: 'Trustpilot — WikiFX reviews', url: 'https://www.trustpilot.com/review/wikifx.com' },
        { label: 'WikiFX official site — About Us page', url: 'https://www.wikifx.com/en/about.html' },
        { label: "WikiFX's denial statement (Medium)", url: 'https://wikifxcom.medium.com/wikifx-denies-they-take-money-from-brokers-for-positive-rankings-d1f1ac40fc79' },
      ],
    },
    wikibit: {
      caseNo: 'CASE No. 002',
      name: 'WikiBit',
      siteUrl: 'https://www.wikibit.com/',
      status: 'critical',
      statusLabel: 'Caution',
      scores: [4, 3, 1, 5, 1, 2],
      notes: [
        "The About page names the operating company as 'COOLBIT CO., LIMITED,' but lists no address or representative. This is more disclosure than WikiFX offers, but still insufficient.",
        "The site publishes a framework it calls a '5-dimension risk scoring model,' but no explanation of the specific calculation method or weighting could be found.",
        'No disclosure of a revenue model appears anywhere on the site. It is covered by the same DL News investigation as sister site WikiFX.',
        'Trustpilot review volume is still low (5 reviews, averaging 3.1/5); this audit found no strong evidence regarding review authenticity.',
        "DL News's investigation named the site specifically, reporting that it gives high ratings to crypto exchanges flagged by regulators and portrays advertiser companies' regulatory standing more favorably than it actually is.",
        'In addition to the DL News investigation (which mentions the site in the same article as WikiFX), complaints about fund-related disputes can be found on Trustpilot. The number of independent sources is not as large as for WikiFX.',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Trustpilot — WikiBit reviews', url: 'https://www.trustpilot.com/review/wikibit.com' },
        { label: 'WikiBit official site — About', url: 'https://www.wikibit.com/about' },
      ],
    },
    fpa: {
      caseNo: 'CASE No. 003',
      name: 'Forex Peace Army',
      siteUrl: 'https://www.forexpeacearmy.com/',
      status: 'warn',
      statusLabel: 'Some Concerns',
      scores: [7, 6, 6, 4, 6, 4],
      notes: [
        'It is publicly disclosed that Dmitri Chavkerov founded the site in 2005, with its base explicitly stated as New York, USA. Unlike WikiFX/WikiBit, a named individual operator can be identified.',
        "The site discloses manual review screening, fact-checking with brokers, and a dispute-resolution process between parties called the 'FPA Traders Court.' However, the actual numerical scoring formula is not disclosed.",
        'The site states explicitly that it earns revenue from advertising but that this does not constitute endorsement of the advertised products. The disclosure itself is relatively thorough by industry standards. However, independent articles and users repeatedly allege that advertisers receive favorable treatment.',
        "Its manual moderation and broker-verification process go further than other sites, but criticism of advertiser favoritism is common, and its Trustpilot rating is 'Bad' at 1.2/5.",
        'This audit found no clear cases of inconsistency with published regulatory data (a provisional assessment, as an exhaustive check was not performed).',
        "Finance Magnates investigated the site's operations in an article titled 'Bullets and Bribes.' Disputes over defamatory content are common enough that multiple legal services specializing in review-removal have sprung up around it.",
      ],
      sources: [
        { label: 'Finance Magnates — Bullets and Bribes: A Look into the World of the Forex Peace Army', url: 'https://www.financemagnates.com/executives/interview/bullets-and-bribes-a-look-into-the-world-of-the-forex-peace-army/' },
        { label: 'Forex Peace Army — Advertising page (revenue model)', url: 'https://www.forexpeacearmy.com/ad' },
        { label: 'Trustpilot — Forex Peace Army reviews', url: 'https://www.trustpilot.com/review/www.forexpeacearmy.com' },
        { label: 'Lawyerd — Legal commentary on FPA review removal', url: 'https://lawyerd.net/blog/forex-peace-army-review-removal/' },
      ],
    },
    dailyforex: {
      caseNo: 'CASE No. 004',
      name: 'DailyForex',
      siteUrl: 'https://www.dailyforex.com/',
      status: 'good',
      statusLabel: 'Good',
      scores: [7, 7, 7, 5, 6, 7],
      notes: [
        'The official site states the address of operator Global On Media (Delaware, USA) explicitly. It also discloses that it was founded in 2008 and has approximately 19 employees.',
        "It publishes dedicated 'Our Methodology' and 'Why You Can Trust Us' pages, stating explicitly that regulation and safety are weighted most heavily.",
        'It maintains a disclosure page stating explicitly that while it earns advertising revenue, commercial considerations do not affect broker ratings. Affiliate partnerships are also disclosed.',
        'Trustpilot reviews are still few (3), and this audit found no strong evidence regarding authenticity.',
        'This audit found no clear cases of inconsistency with regulatory data (an exhaustive check was not performed).',
        'Within the scope of this audit, no significant problem cases such as lawsuits or administrative sanctions were found.',
      ],
      sources: [
        { label: 'DailyForex — About Us', url: 'https://www.dailyforex.com/aboutus' },
        { label: 'DailyForex — Our Methodology', url: 'https://www.dailyforex.com/our-methodology' },
        { label: 'DailyForex — Why You Can Trust Our Content', url: 'https://www.dailyforex.com/why-trust-us' },
        { label: 'Trustpilot — DailyForex reviews', url: 'https://www.trustpilot.com/review/dailyforex.com' },
      ],
    },
    tradersunion: {
      caseNo: 'CASE No. 005',
      name: 'Traders Union',
      siteUrl: 'https://tradersunion.com/',
      status: 'warn',
      statusLabel: 'Some Concerns',
      scores: [5, 6, 6, 3, 6, 4],
      notes: [
        'Its base is disclosed as Limassol, Cyprus, but no founder or representative name could be confirmed.',
        'It publishes a framework combining multiple metrics, including a User Reviews Score, Loyalty Index, Popularity Score, and Web Mention Index.',
        "It discloses revenue from advertising and partner programs, and claims that 'writers do not have access to advertiser data.'",
        "While it publishes its own 'Combating Fake Reviews' policy page, multiple Trustpilot posts allege that it favors advertisers. In addition, the Forex Peace Army community has an allegation that it threatened to post negative content unless paid (note: this is an unverified third-party allegation).",
        'This audit found no clear cases of inconsistency with regulatory data (an exhaustive check was not performed).',
        'The main case is the above allegation of intimidation raised in the FPA community. No confirmation by public authorities or investigative reporting by major media outlets was found.',
      ],
      sources: [
        { label: 'Traders Union — Combating Fake Reviews Policy', url: 'https://tradersunion.com/combating-fake-reviews/' },
        { label: 'Trustpilot — Traders Union reviews', url: 'https://www.trustpilot.com/review/tradersunion.com' },
        { label: 'Forex Peace Army — Traders Union review thread', url: 'https://www.forexpeacearmy.com/forex-reviews/8243/www.tradersunion.com' },
      ],
    },
    forexratings: {
      caseNo: 'CASE No. 006',
      name: 'Forex-Ratings.com',
      siteUrl: 'https://www.forex-ratings.com/',
      status: 'critical',
      statusLabel: 'Caution',
      scores: [2, 4, 2, 5, 5, 5],
      notes: [
        "The official About page lists no operating company name, address, or representative — only a 'Contact us' link.",
        "It explains a policy of 'incorporating a voting mechanism to reflect changes in broker popularity over multiple periods,' but the specific calculation formula is not disclosed.",
        'No disclosure regarding advertising or sponsorships could be found.',
        'This audit found no strong evidence regarding authenticity (provisional assessment).',
        'This audit found no clear cases of inconsistency with regulatory data (provisional assessment).',
        'Within the scope of this audit, no specific problem cases were found (provisional assessment; the lack of transparency in operator information is itself a risk factor).',
      ],
      sources: [
        { label: 'Forex-Ratings.com — About Forex Ratings', url: 'https://www.forex-ratings.com/company/about-forex-ratings/' },
      ],
    },
    fxtrustscore: {
      caseNo: 'CASE No. 007',
      name: 'FX Trust Score',
      siteUrl: 'https://www.fxtrustscore.com/',
      status: 'good',
      statusLabel: 'Good',
      scores: [8, 7, 7, 6, 6, 6],
      notes: [
        'The official site states the operating company, Cheyne Media Ltd (registered in Gibraltar, registration number 122915), and even the background of founder Anthea Michael. Among the sites examined in this audit, its disclosure level is high.',
        'It calculates scores based on a published proprietary methodology and maintains a policy page stating explicitly that scores do not change based on payment or partnership.',
        'It maintains a dedicated page disclosing its advertising and affiliate relationships while stating explicitly that these are kept separate from scoring.',
        'Disclosure levels are high, but because the site is relatively new, there are still few cases of independent third-party verification.',
        'This audit found no clear cases of inconsistency with regulatory data.',
        'Within the scope of this audit, no specific problem cases were found (note: because the site is new, there are few public verification cases to draw on in general).',
      ],
      sources: [
        { label: 'FX Trust Score — About Us', url: 'https://www.fxtrustscore.com/about-us/' },
        { label: 'FX Trust Score — Disclosures', url: 'https://www.fxtrustscore.com/disclosures/' },
      ],
    },
    compareforexbrokers: {
      caseNo: 'CASE No. 008',
      name: 'CompareForexBrokers',
      siteUrl: 'https://www.compareforexbrokers.com/',
      status: 'good',
      statusLabel: 'Good',
      scores: [9, 7, 8, 6, 6, 7],
      notes: [
        'It discloses the real names of founders Justin Grossbard and Noam Korbl, its base in Melbourne, Australia, and even its ABN registration number. This is the highest disclosure level among the sites examined in this audit.',
        "Its 'Our Methodology' page explains the specific factors used in its ratings.",
        "A dedicated 'Advertiser Disclosure' page explains its partnership-fee structure and states that its writing and research team does not know which brokers pay partnership fees, describing this separation of duties.",
        'It has an established track record on Trustpilot, with over 37 reviews averaging 4/5. This audit found no serious authenticity issues.',
        'This audit found no clear cases of inconsistency with regulatory data.',
        'Within the scope of this audit, no major controversies were found.',
      ],
      sources: [
        { label: 'CompareForexBrokers — About Us', url: 'https://www.compareforexbrokers.com/about-us/' },
        { label: 'CompareForexBrokers — Advertiser Disclosure', url: 'https://www.compareforexbrokers.com/about-us/advertiser-disclosure/' },
        { label: 'CompareForexBrokers — Our Methodology', url: 'https://www.compareforexbrokers.com/our-methodology/' },
      ],
    },
    forexbrokerscom: {
      caseNo: 'CASE No. 009',
      name: 'ForexBrokers.com',
      siteUrl: 'https://www.forexbrokers.com/',
      status: 'good',
      statusLabel: 'Good',
      scores: [8, 7, 6, 5, 6, 6],
      notes: [
        'It discloses its operator, Reink Media Group, LLC (Michigan, USA, founded 2009). The company is also a third-party-certified B Corporation.',
        "A dedicated page titled 'How We Calculate Forex Broker Trust' explains the factors behind its trust score.",
        'B Corp certification signals a degree of commitment to the public interest, but this audit could not confirm a detailed disclosure page for advertising revenue.',
        'One Trustpilot post raising concerns about the volume of advertising and its impact on neutrality could be found (a single case, not enough to call a pattern).',
        'This audit found no clear cases of inconsistency with regulatory data.',
        'Within the scope of this audit, no major controversies were found.',
      ],
      sources: [
        { label: 'ForexBrokers.com — About Us', url: 'https://www.forexbrokers.com/about' },
        { label: 'ForexBrokers.com — How We Calculate Forex Broker Trust', url: 'https://www.forexbrokers.com/trust-score' },
        { label: 'Reink Media Group — B Corporation profile', url: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/reink-media-group-llc/' },
      ],
    },
    brokerchooser: {
      caseNo: 'CASE No. 010',
      name: 'BrokerChooser',
      siteUrl: 'https://brokerchooser.com/',
      status: 'warn',
      statusLabel: 'Some Concerns',
      scores: [8, 7, 5, 4, 6, 4],
      notes: [
        'It discloses the real names of founders Tibor Bedő and Gergely Ferencz Korpos and its base in Budapest, Hungary.',
        "Its 'methodology' and 'why trust us' pages explain the rating process.",
        "It maintains an 'Advertiser Disclosure' page, but some critics point out that its explanation of the revenue model is insufficient.",
        'Multiple Trustpilot posts can be found alleging that affiliate revenue is linked to recommendation rankings, and reporting losses on recommended brokers.',
        'This audit found no clear cases of inconsistency with regulatory data.',
        'The main cases are the complaint pattern on Trustpilot noted above. No investigative reporting by major media outlets was confirmed.',
      ],
      sources: [
        { label: 'BrokerChooser — Advertiser Disclosure', url: 'https://brokerchooser.com/advertiser-disclosure' },
        { label: 'BrokerChooser — Online broker review methodology', url: 'https://brokerchooser.com/methodology' },
        { label: 'Trustpilot — BrokerChooser reviews', url: 'https://www.trustpilot.com/review/brokerchooser.com' },
      ],
    },
    brokersview: {
      caseNo: 'CASE No. 011',
      name: 'BrokersView',
      siteUrl: 'https://www.brokersview.com/',
      status: 'critical',
      statusLabel: 'Caution',
      scores: [2, 3, 2, 2, 4, 2],
      notes: [
        'The official site itself acknowledges that its office location is undisclosed. Its founding year is also inconsistent across sources, cited as either 2017 or 2022.',
        "It publishes content such as a 'weekly report on fraudulent brokers,' but no specific score-calculation method could be confirmed.",
        'No disclosure of an advertising or revenue model could be found.',
        'Multiple users have reported allegations that negative reviews are not removed even after payment, and that fabricated reviews exist. Its overall Trustpilot rating is also low, at 1.5.',
        'This audit did not confirm any direct cases of inconsistency with regulatory data.',
        'Multiple user accusations can be found alleging that the site takes money from brokers to disparage their competitors — a pattern similar to that alleged against WikiFX.',
      ],
      sources: [
        { label: 'Trustpilot — BrokersView reviews', url: 'https://www.trustpilot.com/review/www.brokersview.com' },
        { label: 'BrokersView — About Us', url: 'https://www.brokersview.com/about-us' },
        { label: 'Finance Scam — BrokersView: A Critical Review', url: 'https://www.financescam.com/2024/12/19/brokersview-a-critical-review/' },
      ],
    },
    forexbrokerrating: {
      caseNo: 'CASE No. 012',
      name: 'Forex-Broker-Rating.com',
      siteUrl: 'https://www.forex-broker-rating.com/',
      status: 'critical',
      statusLabel: 'Caution',
      scores: [2, 3, 2, 4, 5, 5],
      notes: [
        "The official site shows only a copyright notice reading '© 2009-2026 Forex Broker Rating.com,' with no operating company name or address to be found.",
        'The rating format appears to be based on broker self-registration and user voting (based on general industry information). No specific scoring formula could be confirmed.',
        'No disclosure of an advertising or revenue model could be found.',
        'The self-registration-plus-voting format inherently carries a structural risk of fraudulent voting, but this audit found no specific evidence of manipulation.',
        'This audit found no clear cases of inconsistency with regulatory data (provisional assessment).',
        'Within the scope of this audit, no specific problem cases were found (note: the site itself offers little information, which limits the thoroughness of this review).',
      ],
      sources: [
        { label: 'Forex-Broker-Rating.com (Russian-language edition)', url: 'https://www.forex-broker-rating.com/ru' },
      ],
    },
    daman: {
      caseNo: 'CASE No. 013',
      name: 'Daman（ضمان）',
      siteUrl: 'https://daman.reviews/',
      status: 'critical',
      statusLabel: 'Caution',
      scores: [2, 3, 2, 5, 5, 5],
      notes: [
        'The official site lists no operating company name, address, or representative — only an email address could be confirmed.',
        "A link to a page equivalent to a 'rating policy' exists, but the details of its content could not be confirmed.",
        'No disclosure of an advertising or revenue model could be found.',
        'This audit found no strong evidence regarding authenticity (provisional assessment, as the site itself offers little information).',
        'This audit found no clear cases of inconsistency with regulatory data (provisional assessment).',
        'Within the scope of this audit, no specific problem cases were found (note: as a small site in the Arabic-speaking region, the thoroughness of this review has limits).',
      ],
      sources: [
        { label: 'Daman — Broker review listing', url: 'https://daman.reviews/forex-brokers' },
      ],
    },
    seputarforex: {
      caseNo: 'CASE No. 014',
      name: 'Seputar Forex',
      siteUrl: 'https://www.seputarforex.net/',
      status: 'warn',
      statusLabel: 'Some Concerns',
      scores: [4, 4, 4, 5, 6, 5],
      notes: [
        'The official site\'s operator-information page could not be accessed directly (broken link), so the operating company name and representative could not be confirmed.',
        'This audit found no disclosure of a specific scoring method or rating logic.',
        'This audit found no explicit disclosure of an advertising or revenue model.',
        'This audit found no strong evidence regarding authenticity (as the information is in Indonesian, the thoroughness of English-language searches has limits).',
        'The fact that it includes brokers registered with the local regulator (Bappebti) among its listings is a somewhat positive factor from the standpoint of consistency with regulatory information.',
        'Within the scope of this audit, no specific problem cases were found (note the same limits on thoroughness described above).',
      ],
      sources: [
        { label: 'Seputar Forex — Broker review listing', url: 'https://www.seputarforex.net/broker/forex/review' },
      ],
    },
    fxscouts: {
      caseNo: 'CASE No. 015',
      name: 'FX Scouts',
      siteUrl: 'https://fxscouts.com/',
      status: 'good',
      statusLabel: 'Good',
      scores: [7, 6, 6, 6, 6, 6],
      notes: [
        'The official site states explicitly its operator, FxScouts Group AB (registered in Sweden, founded 2011).',
        "It publishes a framework of 'Broker Score' and 'Trust Rating.' For prop firm evaluations, it also explains its verification process.",
        'It states itself that it operates on affiliate revenue alone and discloses these relationships explicitly.',
        'One third-party article claiming the site is fraudulent was found, but given the low credibility of its source and lack of supporting evidence, this is not treated as established fact.',
        'This audit found no clear cases of inconsistency with regulatory data.',
        'Aside from the one unverified critical article noted above, no major controversies were found.',
      ],
      sources: [
        { label: 'FxScouts — About Us', url: 'https://fxscouts.com/about-us/' },
      ],
    },
  };

  const AUDIT_DATE = '2026-09-18'; // Date of this audit round (sites that undergo re-review will have entries added to the history field in SITE_DATA)
