  const AXES6 = ['透明性', 'ロジック公開', '収益開示', '真正性対策', '当局整合性', '過去事例'];
  const AXIS_FULL_NAMES = ['運営者情報の透明性', '評価ロジックの公開性', '収益モデルの開示', 'レビューの真正性対策', '規制当局データとの整合性', '過去の問題事例'];

  // ---------- 調査済み案件データ（軸の並び順はAXES6/AXIS_FULL_NAMESと同じ） ----------
  const SITE_DATA = {
    wikifx: {
      caseNo: 'CASE No. 001',
      name: 'WikiFX',
      status: 'unrecommended',
      statusLabel: '非推奨',
      scores: [1, 3, 1, 2, 1, 1],
      notes: [
        '公式サイトの会社概要に会社名・所在地・代表者の記載なし（連絡先のみ）。香港証券先物委員会(SFC)が「同社の名乗る香港住所は実在せず、正規企業の情報を無断使用している疑いがある」と公式に警告。',
        '「License/Regulation/Risk Control/Business/Software」の5指標という枠組みは公開。ただし詳細な算出方法は非公開で、複数の報道が「尋ねても説明がない」と指摘。',
        'サイト上に収益モデルの開示は一切なし。調査報道DL Newsが入手した内部資料によれば、業者に最大$128,000を要求し、支払えば高評価・拒否すれば低評価という構図が報じられている（同社は否定）。',
        '未検証の投稿がそのまま反映されるとの報告多数。Trustpilotでの評価も「Poor」2/5。',
        'FCA・CySEC等の正規ライセンス業者を「無登録」「疑わしい」と誤表示する事例が多数報告。加えて自社の登録住所自体が香港SFCにより「実在しない」と指摘されている。',
        'DL Newsの調査報道、香港SFCの公式警告、姉妹サイトWikiBitも同様の疑惑で報道、複数業者による公開告発——独立した根拠が複数存在する。',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Finance Magnates — Hong Kong SFC warns of WikiFX', url: 'https://www.financemagnates.com/forex/hong-kong-continues-to-scrutinize-fx-space-warns-of-wikifx/' },
        { label: 'Trustpilot — WikiFX reviews', url: 'https://www.trustpilot.com/review/wikifx.com' },
        { label: 'WikiFX公式サイト — 会社概要ページ', url: 'https://www.wikifx.com/en/about.html' },
        { label: 'WikiFXによる否定声明（Medium）', url: 'https://wikifxcom.medium.com/wikifx-denies-they-take-money-from-brokers-for-positive-rankings-d1f1ac40fc79' },
      ],
    },
    wikibit: {
      caseNo: 'CASE No. 002',
      name: 'WikiBit',
      status: 'critical',
      statusLabel: '要注意',
      scores: [4, 3, 1, 5, 1, 2],
      notes: [
        '会社概要ページに運営会社名「COOLBIT CO., LIMITED」の記載はあるが、所在地・代表者名の記載はなし。WikiFXよりは開示があるが不十分。',
        '「5側面のリスク採点モデル」という枠組みは公開しているが、具体的な計算方法・重み付けの説明は見当たらない。',
        'サイト上に収益モデルの開示は一切なし。姉妹サイトWikiFXと同じ調査報道(DL News)の対象になっている。',
        'Trustpilotのレビュー数はまだ少なく（5件、平均3.1/5）、レビューの真正性について強い根拠となる報告は今回の調査では見つからなかった。',
        'DL Newsの調査で「規制当局から懸念を指摘された暗号資産取引所に高評価を与えている」「広告主企業の規制状況を実際より良く見せている」と名指しで報道された。',
        'DL Newsの調査報道（WikiFXと同一記事内で言及）に加え、Trustpilotに資金トラブルの苦情投稿が確認できる。WikiFXほど独立した根拠の数は多くない。',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Trustpilot — WikiBit reviews', url: 'https://www.trustpilot.com/review/wikibit.com' },
        { label: 'WikiBit公式サイト — About', url: 'https://www.wikibit.com/about' },
      ],
    },
    fpa: {
      caseNo: 'CASE No. 003',
      name: 'Forex Peace Army',
      status: 'warn',
      statusLabel: '一部懸念',
      scores: [7, 6, 6, 4, 6, 4],
      notes: [
        '2005年にDmitri Chavkerov氏が設立したことが公開されており、拠点も米国ニューヨークと明記。WikiFX/WikiBitと異なり運営者個人を実名で特定できる。',
        '人力によるレビュー審査、業者への事実確認、「FPA Traders Court」という当事者間の是正プロセスを公開。ただし数値化された算出式そのものは非公開。',
        '自社サイト上で「広告表示で収益を得ているが、広告商品を推奨するものではない」と明記。開示自体は業界内では丁寧な部類。ただし広告出稿業者が優遇されているとの指摘が独立系記事や利用者から繰り返し出ている。',
        '人力モデレーションと業者への確認プロセスを実施している点は他サイトより踏み込んでいるが、広告主優遇の批判が多く、Trustpilotでも「Bad」1.2/5。',
        '今回の調査では、規制当局の公表データとの明確な不一致事例は確認できなかった（網羅的な検証は未実施のため暫定評価）。',
        'Finance Magnatesが「Bullets and Bribes」という調査記事で運営実態を取材。掲載内容を巡る名誉毀損トラブルが多く、専門の削除代行を謳う法律サービスが複数存在するほど紛争化している。',
      ],
      sources: [
        { label: 'Finance Magnates — Bullets and Bribes: A Look into the World of the Forex Peace Army', url: 'https://www.financemagnates.com/executives/interview/bullets-and-bribes-a-look-into-the-world-of-the-forex-peace-army/' },
        { label: 'Forex Peace Army — 広告ページ（収益モデル）', url: 'https://www.forexpeacearmy.com/ad' },
        { label: 'Trustpilot — Forex Peace Army reviews', url: 'https://www.trustpilot.com/review/www.forexpeacearmy.com' },
        { label: 'Lawyerd — FPAレビュー削除に関する法的解説', url: 'https://lawyerd.net/blog/forex-peace-army-review-removal/' },
      ],
    },
    dailyforex: {
      caseNo: 'CASE No. 004',
      name: 'DailyForex',
      status: 'good',
      statusLabel: '良好',
      scores: [7, 7, 7, 5, 6, 7],
      notes: [
        '運営元Global On Mediaの住所（米デラウェア州）を公式サイトに明記。2008年設立、社員約19名と規模も開示。',
        '「Our Methodology」「Why You Can Trust Us」という専用ページを公開し、規制・安全性を最重要視すると明記。',
        '「広告収入はあるが、商業的事情は業者評価に影響しない」と明記した開示ページを保有。アフィリエイト提携も開示。',
        'Trustpilotのレビューはまだ3件と少なく、真正性について強い根拠となる情報は今回の調査では見つからなかった。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった（網羅的検証は未実施）。',
        '今回の調査範囲では、具体的な訴訟・行政処分などの重大な問題事例は見つからなかった。',
      ],
      sources: [
        { label: 'DailyForex — About Us', url: 'https://www.dailyforex.com/aboutus' },
        { label: 'DailyForex — Our Methodology', url: 'https://www.dailyforex.com/our-methodology' },
        { label: 'DailyForex — Why You Can Trust Our Content', url: 'https://www.dailyforex.com/why-trust-us' },
        { label: 'Trustpilot — DailyForex reviews', url: 'https://www.trustpilot.com/review/dailyforex.com' },
      ],
    },
    tradersunion: {
      caseNo: 'CASE No. 005',
      name: 'Traders Union',
      status: 'warn',
      statusLabel: '一部懸念',
      scores: [5, 6, 6, 3, 6, 4],
      notes: [
        '拠点はキプロス・リマソールと公開されているが、創業者・代表者名は確認できなかった。',
        'User Reviews Score・Loyalty Index・Popularity Score・Web Mention Indexなど複数指標を組み合わせた枠組みを公開。',
        '広告・パートナー参加プログラムによる収益を明記し、「執筆陣は広告主データに触れない」と主張している。',
        '自ら「フェイクレビュー対策方針」ページを公開する一方、Trustpilotでは「広告主を優遇している」との指摘が複数。加えてForex Peace Armyのコミュニティから「支払わなければ否定的な投稿をすると脅した」との申し立てがある（第三者による未検証の申し立てである点に留意）。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった（網羅的検証は未実施）。',
        '上記のFPAコミュニティでの脅迫疑惑の申し立てが主な事例。公的機関による認定や大手メディアの調査報道までは確認できていない。',
      ],
      sources: [
        { label: 'Traders Union — Combating Fake Reviews Policy', url: 'https://tradersunion.com/combating-fake-reviews/' },
        { label: 'Trustpilot — Traders Union reviews', url: 'https://www.trustpilot.com/review/tradersunion.com' },
        { label: 'Forex Peace Army — Traders Union review thread', url: 'https://www.forexpeacearmy.com/forex-reviews/8243/www.tradersunion.com' },
      ],
    },
    forexratings: {
      caseNo: 'CASE No. 006',
      name: 'Forex-Ratings.com',
      status: 'critical',
      statusLabel: '要注意',
      scores: [2, 4, 2, 5, 5, 5],
      notes: [
        '公式の会社概要ページに運営会社名・所在地・代表者の記載がなく、「Contact us」リンクのみ。',
        '「投票メカニズムを組み込み、複数期間の業者人気の変化を反映する」という方針説明はあるが、具体的な計算式は非公開。',
        '広告・スポンサーシップに関する開示は見当たらない。',
        '今回の調査では真正性について強い根拠となる情報は見つからなかった（暫定評価）。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった（暫定評価）。',
        '今回の調査範囲では具体的な問題事例は見つからなかった（暫定評価。運営情報の不透明さ自体はリスク要因）。',
      ],
      sources: [
        { label: 'Forex-Ratings.com — About Forex Ratings', url: 'https://www.forex-ratings.com/company/about-forex-ratings/' },
      ],
    },
    fxtrustscore: {
      caseNo: 'CASE No. 007',
      name: 'FX Trust Score',
      status: 'good',
      statusLabel: '良好',
      scores: [8, 7, 7, 6, 6, 6],
      notes: [
        '運営会社Cheyne Media Ltd（ジブラルタル登録、登録番号122915）と創業者Anthea Michael氏の経歴まで公式サイトに明記。今回調査した中でも開示水準は高い。',
        '独自の公開手法に基づきスコアを算出し「支払い・提携によってスコアは変動しない」と明記した方針ページを保有。',
        '広告・アフィリエイト関係を開示した上で、スコアリングとは分離すると明記する専用ページを保有。',
        '開示水準は高いが、比較的新しいサイトのため第三者による独立検証の事例がまだ少ない。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった。',
        '今回の調査範囲では具体的な問題事例は見つからなかった（新しいサイトのため公的な検証事例自体が少ない点に留意）。',
      ],
      sources: [
        { label: 'FX Trust Score — About Us', url: 'https://www.fxtrustscore.com/about-us/' },
        { label: 'FX Trust Score — Disclosures', url: 'https://www.fxtrustscore.com/disclosures/' },
      ],
    },
    compareforexbrokers: {
      caseNo: 'CASE No. 008',
      name: 'CompareForexBrokers',
      status: 'good',
      statusLabel: '良好',
      scores: [9, 7, 8, 6, 6, 7],
      notes: [
        '創業者Justin Grossbard氏・Noam Korbl氏の実名、豪州メルボルン拠点、ABN登録番号まで公開。今回調査した中で最も開示水準が高い。',
        '「Our Methodology」ページで評価要素を具体的に説明している。',
        '専用の「Advertiser Disclosure」ページで、提携料の仕組みと「執筆・調査チームはどの業者が提携料を払っているか知らない」という分離体制を説明。',
        'Trustpilotで37件超のレビュー・4/5と一定の実績あり。今回の調査では深刻な真正性の問題は見つからなかった。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった。',
        '今回の調査範囲では大きな論争は確認できなかった。',
      ],
      sources: [
        { label: 'CompareForexBrokers — About Us', url: 'https://www.compareforexbrokers.com/about-us/' },
        { label: 'CompareForexBrokers — Advertiser Disclosure', url: 'https://www.compareforexbrokers.com/about-us/advertiser-disclosure/' },
        { label: 'CompareForexBrokers — Our Methodology', url: 'https://www.compareforexbrokers.com/our-methodology/' },
      ],
    },
    forexbrokerscom: {
      caseNo: 'CASE No. 009',
      name: 'ForexBrokers.com',
      status: 'good',
      statusLabel: '良好',
      scores: [8, 7, 6, 5, 6, 6],
      notes: [
        '運営元Reink Media Group, LLC（米ミシガン州、2009年設立）を公開。同社は第三者認証のCertified B Corporationでもある。',
        '「How We Calculate Forex Broker Trust」という専用ページでトラストスコアの算出要素を説明。',
        'B Corp認証は公共性への一定のコミットメントを示すが、本調査では広告収益の詳細な開示ページまでは確認できなかった。',
        'Trustpilotに「広告の多さと中立性への疑問」を指摘する投稿が確認できる（1件、パターンとまでは言えない）。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった。',
        '今回の調査範囲では大きな論争は確認できなかった。',
      ],
      sources: [
        { label: 'ForexBrokers.com — About Us', url: 'https://www.forexbrokers.com/about' },
        { label: 'ForexBrokers.com — How We Calculate Forex Broker Trust', url: 'https://www.forexbrokers.com/trust-score' },
        { label: 'Reink Media Group — B Corporation profile', url: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/reink-media-group-llc/' },
      ],
    },
    brokerchooser: {
      caseNo: 'CASE No. 010',
      name: 'BrokerChooser',
      status: 'warn',
      statusLabel: '一部懸念',
      scores: [8, 7, 5, 4, 6, 4],
      notes: [
        '創業者Tibor Bedő氏・Gergely Ferencz Korpos氏の実名、ハンガリー・ブダペスト拠点を公開。',
        '「methodology」「why trust us」ページで評価プロセスを説明。',
        '「Advertiser Disclosure」ページは保有するが、一部の批判者から「収益モデルの説明が不十分」との指摘がある。',
        'Trustpilotに「アフィリエイト収益と推奨順位が結びついている」「推奨業者で損失を出した」という投稿が複数確認できる。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった。',
        '上記のTrustpilot上の苦情パターンが主な事例。大手メディアによる調査報道までは確認できていない。',
      ],
      sources: [
        { label: 'BrokerChooser — Advertiser Disclosure', url: 'https://brokerchooser.com/advertiser-disclosure' },
        { label: 'BrokerChooser — Online broker review methodology', url: 'https://brokerchooser.com/methodology' },
        { label: 'Trustpilot — BrokerChooser reviews', url: 'https://www.trustpilot.com/review/brokerchooser.com' },
      ],
    },
    brokersview: {
      caseNo: 'CASE No. 011',
      name: 'BrokersView',
      status: 'critical',
      statusLabel: '要注意',
      scores: [2, 3, 2, 2, 4, 2],
      notes: [
        '公式サイト自身が「事務所所在地は未公開」と認めている。設立年についても情報源により2017年・2022年と食い違いがある。',
        '「不正業者の週次レポート」のような発信はあるが、具体的なスコア算出方法は確認できなかった。',
        '広告・収益モデルの開示は見当たらない。',
        '複数の利用者から「金銭を払っても否定的なレビューを削除しない」「ねつ造されたレビューがある」との申し立てが報告されている。Trustpilot総合評価も1.5と低い。',
        '今回の調査では規制当局データとの直接的な不一致事例までは確認できなかった。',
        '「業者から金を受け取って競合他社を中傷している」との利用者からの告発が複数確認できる。WikiFXと似た構図が指摘されている。',
      ],
      sources: [
        { label: 'Trustpilot — BrokersView reviews', url: 'https://www.trustpilot.com/review/www.brokersview.com' },
        { label: 'BrokersView — About Us', url: 'https://www.brokersview.com/about-us' },
        { label: 'Finance Scam — BrokersView: A Critical Review', url: 'https://www.financescam.com/2024/12/19/brokersview-a-critical-review/' },
      ],
    },
    forexbrokerrating: {
      caseNo: 'CASE No. 012',
      name: 'Forex-Broker-Rating.com',
      status: 'critical',
      statusLabel: '要注意',
      scores: [2, 3, 2, 4, 5, 5],
      notes: [
        '公式サイトには「© 2009-2026 Forex Broker Rating.com」という著作権表記のみで、運営会社名・所在地の記載が見当たらない。',
        '業者の自己登録とユーザー投票による評価形式（一般的な業界情報からの把握）。具体的な採点式は確認できなかった。',
        '広告・収益モデルの開示は見当たらない。',
        '自己登録＋投票という形式自体はなりすまし票のリスクを構造的に抱えるが、今回の調査で具体的な不正事例は確認できなかった。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった（暫定評価）。',
        '今回の調査範囲では具体的な問題事例は見つからなかった（サイト自体の情報量が少なく、調査の網羅性に限界がある点に留意）。',
      ],
      sources: [
        { label: 'Forex-Broker-Rating.com（ロシア語版）', url: 'https://www.forex-broker-rating.com/ru' },
      ],
    },
    daman: {
      caseNo: 'CASE No. 013',
      name: 'Daman（ضمان）',
      status: 'critical',
      statusLabel: '要注意',
      scores: [2, 3, 2, 5, 5, 5],
      notes: [
        '公式サイトに運営会社名・所在地・代表者の記載はなく、メールアドレスのみ確認できた。',
        '「評価方針」に相当するページへのリンクはあるが、内容の詳細は確認できなかった。',
        '広告・収益モデルの開示は見当たらない。',
        '今回の調査では真正性について強い根拠となる情報は見つからなかった（サイト自体の情報量が少ないため暫定評価）。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった（暫定評価）。',
        '今回の調査範囲では具体的な問題事例は見つからなかった（アラビア語圏の小規模サイトのため、調査の網羅性に限界がある点に留意）。',
      ],
      sources: [
        { label: 'Daman — 業者レビュー一覧', url: 'https://daman.reviews/forex-brokers' },
      ],
    },
    seputarforex: {
      caseNo: 'CASE No. 014',
      name: 'Seputar Forex',
      status: 'warn',
      statusLabel: '一部懸念',
      scores: [4, 4, 4, 5, 6, 5],
      notes: [
        '公式サイトの運営者情報ページに直接アクセスできず（リンク切れ）、運営会社名・代表者の確認ができなかった。',
        '具体的な採点方法・評価ロジックの公開は今回の調査では確認できなかった。',
        '広告・収益モデルの明示的な開示は確認できなかった。',
        '今回の調査では真正性について強い根拠となる情報は見つからなかった（インドネシア語圏の情報のため英語検索での網羅性に限界がある）。',
        '現地の正規当局(Bappebti)登録業者を掲載対象に含めている点は、規制情報との整合性という観点でやや前向きな材料。',
        '今回の調査範囲では具体的な問題事例は見つからなかった（同上の網羅性の限界に留意）。',
      ],
      sources: [
        { label: 'Seputar Forex — 業者レビュー一覧', url: 'https://www.seputarforex.net/broker/forex/review' },
      ],
    },
    fxscouts: {
      caseNo: 'CASE No. 015',
      name: 'FX Scouts',
      status: 'good',
      statusLabel: '良好',
      scores: [7, 6, 6, 6, 6, 6],
      notes: [
        '運営元FxScouts Group AB（スウェーデン登録、2011年設立）を公式サイトに明記。',
        '「Broker Score」「Trust Rating」という枠組みを公開。プロップファーム評価では検証プロセスも説明。',
        '「アフィリエイト収益のみで運営し、関係を明示している」と自ら説明。',
        '「詐欺サイトだ」と主張する第三者記事が1件見つかったが、発信元の信頼性が低く裏付けに乏しいため、事実として断定はしない。',
        '今回の調査では規制当局データとの明確な不一致事例は確認できなかった。',
        '上記の未検証の批判記事1件を除き、大きな論争は確認できなかった。',
      ],
      sources: [
        { label: 'FxScouts — About Us', url: 'https://fxscouts.com/about-us/' },
      ],
    },
  };

  const AUDIT_DATE = '2026-09-18'; // 今回の一斉調査日（再調査が発生したサイトはSITE_DATA側にhistoryを追加していく）
