  const AXES6 = ['Transparansi', 'Logika Terbuka', 'Pengungkapan Pendapatan', 'Keaslian Ulasan', 'Konsistensi Regulator', 'Kasus Masa Lalu'];
  const AXIS_FULL_NAMES = ['Transparansi Informasi Operator', 'Keterbukaan Logika Penilaian', 'Pengungkapan Model Pendapatan', 'Langkah Anti-Ulasan Palsu', 'Konsistensi dengan Data Regulator', 'Kasus Masalah di Masa Lalu'];

  // ---------- Data kasus yang telah diinvestigasi (urutan aspek sama dengan AXES6/AXIS_FULL_NAMES) ----------
  const SITE_DATA = {
    wikifx: {
      caseNo: 'CASE No. 001',
      name: 'WikiFX',
      siteUrl: 'https://www.wikifx.com/',
      jpSupport: true,
      status: 'unrecommended',
      statusLabel: 'Tidak Direkomendasikan',
      scores: [1, 3, 1, 2, 1, 1],
      notes: [
        'Halaman profil perusahaan di situs resmi tidak mencantumkan nama perusahaan, alamat, atau perwakilan (hanya kontak). Securities and Futures Commission (SFC) Hong Kong secara resmi memperingatkan bahwa "alamat Hong Kong yang diklaim perusahaan ini tidak nyata dan diduga menggunakan informasi perusahaan resmi tanpa izin."',
        'Kerangka kerja "License/Regulation/Risk Control/Business/Software" (5 indikator) dipublikasikan. Namun metode perhitungan rincinya tidak diungkapkan, dan beberapa laporan media menyebutkan "tidak ada penjelasan meski ditanyakan".',
        'Tidak ada pengungkapan model pendapatan sama sekali di situs. Menurut dokumen internal yang diperoleh media investigasi DL News, perusahaan ini dilaporkan meminta hingga $128.000 dari broker — memberi skor tinggi jika membayar, skor rendah jika menolak (perusahaan membantah hal ini).',
        'Banyak laporan menyebutkan postingan yang belum diverifikasi langsung ditampilkan apa adanya. Skor di Trustpilot juga "Poor" 2/5.',
        'Banyak kasus dilaporkan di mana broker berlisensi resmi seperti FCA/CySEC ditampilkan secara keliru sebagai "tidak terdaftar" atau "mencurigakan". Selain itu, alamat terdaftar perusahaan ini sendiri disebut "tidak nyata" oleh SFC Hong Kong.',
        'Laporan investigasi DL News, peringatan resmi SFC Hong Kong, situs saudari WikiBit yang diberitakan dengan dugaan serupa, serta tuduhan publik dari berbagai broker — terdapat banyak sumber independen yang saling mendukung.',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Finance Magnates — Hong Kong SFC warns of WikiFX', url: 'https://www.financemagnates.com/forex/hong-kong-continues-to-scrutinize-fx-space-warns-of-wikifx/' },
        { label: 'Trustpilot — WikiFX reviews', url: 'https://www.trustpilot.com/review/wikifx.com' },
        { label: 'Situs resmi WikiFX — Halaman profil perusahaan', url: 'https://www.wikifx.com/en/about.html' },
        { label: 'Pernyataan bantahan WikiFX (Medium)', url: 'https://wikifxcom.medium.com/wikifx-denies-they-take-money-from-brokers-for-positive-rankings-d1f1ac40fc79' },
      ],
    },
    wikibit: {
      caseNo: 'CASE No. 002',
      name: 'WikiBit',
      siteUrl: 'https://www.wikibit.com/',
      jpSupport: true,
      status: 'critical',
      statusLabel: 'Perlu Diwaspadai',
      scores: [4, 3, 1, 5, 1, 2],
      notes: [
        'Halaman profil perusahaan mencantumkan nama operator "COOLBIT CO., LIMITED", tetapi tidak ada alamat atau nama perwakilan. Pengungkapan lebih baik dibanding WikiFX, tetapi masih belum memadai.',
        'Kerangka kerja "model penilaian risiko 5 aspek" dipublikasikan, tetapi metode perhitungan dan pembobotan rincinya tidak ditemukan.',
        'Tidak ada pengungkapan model pendapatan sama sekali di situs. Menjadi objek laporan investigasi DL News yang sama dengan situs saudarinya, WikiFX.',
        'Jumlah ulasan di Trustpilot masih sedikit (5 ulasan, rata-rata 3,1/5); tidak ditemukan bukti kuat terkait keaslian ulasan dalam investigasi kali ini.',
        'Investigasi DL News secara spesifik menyebut situs ini "memberi skor tinggi pada bursa kripto yang telah ditandai regulator" dan "menampilkan status regulasi perusahaan pengiklan lebih baik dari kenyataan".',
        'Selain laporan investigasi DL News (disebut dalam artikel yang sama dengan WikiFX), ditemukan pula keluhan soal masalah keuangan di Trustpilot. Jumlah sumber independen tidak sebanyak WikiFX.',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Trustpilot — WikiBit reviews', url: 'https://www.trustpilot.com/review/wikibit.com' },
        { label: 'Situs resmi WikiBit — About', url: 'https://www.wikibit.com/about' },
      ],
    },
    fpa: {
      caseNo: 'CASE No. 003',
      name: 'Forex Peace Army',
      siteUrl: 'https://www.forexpeacearmy.com/',
      status: 'warn',
      statusLabel: 'Ada Kekhawatiran',
      scores: [7, 6, 6, 4, 6, 4],
      notes: [
        'Diketahui secara terbuka bahwa situs ini didirikan oleh Dmitri Chavkerov pada 2005, dengan basis di New York, AS. Berbeda dari WikiFX/WikiBit, individu operatornya dapat diidentifikasi dengan nama asli.',
        'Mempublikasikan proses peninjauan ulasan secara manual, verifikasi fakta ke broker, dan proses penyelesaian sengketa "FPA Traders Court". Namun rumus perhitungan skor itu sendiri tidak diungkapkan.',
        'Situs secara eksplisit menyatakan "mendapat pendapatan dari iklan, tetapi tidak merekomendasikan produk yang diiklankan". Pengungkapannya tergolong cukup baik di industri ini. Namun ada tuduhan berulang dari artikel independen dan pengguna bahwa pengiklan mendapat perlakuan istimewa.',
        'Proses moderasi manual dan verifikasi ke broker lebih maju dibanding situs lain, tetapi banyak kritik soal keberpihakan pada pengiklan, dan skor Trustpilot juga "Bad" 1,2/5.',
        'Dalam investigasi kali ini, tidak ditemukan kasus ketidaksesuaian yang jelas dengan data resmi regulator (penilaian bersifat sementara karena verifikasi menyeluruh belum dilakukan).',
        'Finance Magnates meliput realitas operasional situs ini dalam artikel investigasi "Bullets and Bribes". Banyak sengketa pencemaran nama baik terkait konten yang dimuat, hingga muncul beberapa layanan hukum yang mengkhususkan diri dalam penghapusan ulasan.',
      ],
      sources: [
        { label: 'Finance Magnates — Bullets and Bribes: A Look into the World of the Forex Peace Army', url: 'https://www.financemagnates.com/executives/interview/bullets-and-bribes-a-look-into-the-world-of-the-forex-peace-army/' },
        { label: 'Forex Peace Army — Halaman iklan (model pendapatan)', url: 'https://www.forexpeacearmy.com/ad' },
        { label: 'Trustpilot — Forex Peace Army reviews', url: 'https://www.trustpilot.com/review/www.forexpeacearmy.com' },
        { label: 'Lawyerd — Penjelasan hukum terkait penghapusan ulasan FPA', url: 'https://lawyerd.net/blog/forex-peace-army-review-removal/' },
      ],
    },
    dailyforex: {
      caseNo: 'CASE No. 004',
      name: 'DailyForex',
      siteUrl: 'https://www.dailyforex.com/',
      status: 'good',
      statusLabel: 'Baik',
      scores: [7, 7, 7, 5, 6, 7],
      notes: [
        'Alamat operator Global On Media (Delaware, AS) dicantumkan di situs resmi. Didirikan 2008, jumlah karyawan sekitar 19 orang juga diungkapkan.',
        'Mempublikasikan halaman khusus "Our Methodology" dan "Why You Can Trust Us" yang menyatakan regulasi dan keamanan sebagai prioritas utama.',
        'Memiliki halaman pengungkapan yang menyatakan "ada pendapatan iklan, tetapi kepentingan komersial tidak memengaruhi penilaian broker". Kemitraan afiliasi juga diungkapkan.',
        'Ulasan di Trustpilot masih sedikit (3 ulasan); tidak ditemukan informasi kuat terkait keaslian ulasan dalam investigasi kali ini.',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini (verifikasi menyeluruh belum dilakukan).',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah serius seperti tuntutan hukum atau sanksi administratif.',
      ],
      sources: [
        { label: 'DailyForex — About Us', url: 'https://www.dailyforex.com/aboutus' },
        { label: 'DailyForex — Our Methodology', url: 'https://www.dailyforex.com/our-methodology' },
        { label: 'DailyForex — Why You Can Trust Our Content', url: 'https://www.dailyforex.com/why-trust-us' },
        { label: 'Trustpilot — DailyForex reviews', url: 'https://www.trustpilot.com/review/dailyforex.com' },
      ],
    },
    tradersunion: {
      caseNo: 'CASE No. 005',
      name: 'Traders Union',
      siteUrl: 'https://tradersunion.com/',
      status: 'warn',
      statusLabel: 'Ada Kekhawatiran',
      scores: [5, 6, 6, 3, 6, 4],
      notes: [
        'Basis operasional diungkapkan di Limassol, Siprus, tetapi nama pendiri/perwakilan tidak dapat dikonfirmasi.',
        'Mempublikasikan kerangka kerja yang menggabungkan beberapa indikator seperti User Reviews Score, Loyalty Index, Popularity Score, dan Web Mention Index.',
        'Menyatakan secara eksplisit mendapat pendapatan dari iklan dan program mitra, serta mengklaim "tim penulis tidak mengakses data pengiklan".',
        'Meski mempublikasikan halaman kebijakan "anti-ulasan palsu" sendiri, ada beberapa keluhan di Trustpilot soal "keberpihakan pada pengiklan". Selain itu, komunitas Forex Peace Army pernah mengajukan tuduhan bahwa situs ini "mengancam akan memberi ulasan negatif jika tidak dibayar" (perlu dicatat bahwa ini tuduhan pihak ketiga yang belum diverifikasi).',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini (verifikasi menyeluruh belum dilakukan).',
        'Tuduhan ancaman di komunitas FPA di atas adalah kasus utama yang ditemukan. Belum ada pengakuan lembaga resmi atau liputan investigasi media besar yang dapat dikonfirmasi.',
      ],
      sources: [
        { label: 'Traders Union — Combating Fake Reviews Policy', url: 'https://tradersunion.com/combating-fake-reviews/' },
        { label: 'Trustpilot — Traders Union reviews', url: 'https://www.trustpilot.com/review/tradersunion.com' },
        { label: 'Forex Peace Army — Traders Union review thread', url: 'https://www.forexpeacearmy.com/forex-reviews/8243/www.tradersunion.com' },
      ],
    },
    forexratings: {
      caseNo: 'CASE No. 006',
      name: 'Forex-Ratings.com',
      siteUrl: 'https://www.forex-ratings.com/',
      jpSupport: true,
      status: 'critical',
      statusLabel: 'Perlu Diwaspadai',
      scores: [2, 4, 2, 5, 5, 5],
      notes: [
        'Halaman profil perusahaan resmi tidak mencantumkan nama perusahaan operator, alamat, atau perwakilan — hanya ada tautan "Contact us".',
        'Ada penjelasan kebijakan bahwa situs ini "menggabungkan mekanisme voting untuk mencerminkan perubahan popularitas broker dari waktu ke waktu", tetapi rumus perhitungan spesifiknya tidak diungkapkan.',
        'Tidak ditemukan pengungkapan terkait iklan atau sponsor.',
        'Tidak ditemukan informasi kuat terkait keaslian ulasan dalam investigasi kali ini (penilaian bersifat sementara).',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini (penilaian bersifat sementara).',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah spesifik (penilaian bersifat sementara; ketidaktransparanan informasi operator itu sendiri merupakan faktor risiko).',
      ],
      sources: [
        { label: 'Forex-Ratings.com — About Forex Ratings', url: 'https://www.forex-ratings.com/company/about-forex-ratings/' },
      ],
    },
    fxtrustscore: {
      caseNo: 'CASE No. 007',
      name: 'FX Trust Score',
      siteUrl: 'https://www.fxtrustscore.com/',
      status: 'good',
      statusLabel: 'Baik',
      scores: [8, 7, 7, 6, 6, 6],
      notes: [
        'Perusahaan operator Cheyne Media Ltd (terdaftar di Gibraltar, nomor registrasi 122915) dan latar belakang pendiri Anthea Michael dicantumkan secara lengkap di situs resmi. Tingkat pengungkapan tertinggi di antara yang diinvestigasi kali ini.',
        'Memiliki halaman kebijakan yang menyatakan skor dihitung berdasarkan metode publik miliknya sendiri dan "tidak berubah karena pembayaran atau kemitraan".',
        'Memiliki halaman khusus yang mengungkapkan hubungan iklan/afiliasi sekaligus menyatakan hal itu dipisahkan dari proses penilaian.',
        'Tingkat pengungkapan tinggi, tetapi karena situs relatif baru, kasus verifikasi independen oleh pihak ketiga masih sedikit.',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini.',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah spesifik (perlu dicatat bahwa situs ini masih baru sehingga kasus verifikasi publik sendiri masih sedikit).',
      ],
      sources: [
        { label: 'FX Trust Score — About Us', url: 'https://www.fxtrustscore.com/about-us/' },
        { label: 'FX Trust Score — Disclosures', url: 'https://www.fxtrustscore.com/disclosures/' },
      ],
    },
    compareforexbrokers: {
      caseNo: 'CASE No. 008',
      name: 'CompareForexBrokers',
      siteUrl: 'https://www.compareforexbrokers.com/',
      status: 'good',
      statusLabel: 'Baik',
      scores: [9, 7, 8, 6, 6, 7],
      notes: [
        'Nama asli pendiri Justin Grossbard dan Noam Korbl, basis di Melbourne Australia, hingga nomor registrasi ABN diungkapkan. Tingkat pengungkapan tertinggi di antara yang diinvestigasi kali ini.',
        'Halaman "Our Methodology" menjelaskan secara konkret elemen-elemen penilaian.',
        'Halaman khusus "Advertiser Disclosure" menjelaskan mekanisme biaya kemitraan serta sistem pemisahan bahwa "tim penulis/riset tidak mengetahui broker mana yang membayar biaya kemitraan".',
        'Memiliki rekam jejak yang cukup baik di Trustpilot (37+ ulasan, 4/5). Tidak ditemukan masalah keaslian yang serius dalam investigasi kali ini.',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini.',
        'Tidak ditemukan kontroversi besar dalam cakupan investigasi kali ini.',
      ],
      sources: [
        { label: 'CompareForexBrokers — About Us', url: 'https://www.compareforexbrokers.com/about-us/' },
        { label: 'CompareForexBrokers — Advertiser Disclosure', url: 'https://www.compareforexbrokers.com/about-us/advertiser-disclosure/' },
        { label: 'CompareForexBrokers — Our Methodology', url: 'https://www.compareforexbrokers.com/our-methodology/' },
      ],
    },
    forexbrokerscom: {
      caseNo: 'CASE No. 009',
      name: 'ForexBrokers.com',
      siteUrl: 'https://www.forexbrokers.com/',
      status: 'good',
      statusLabel: 'Baik',
      scores: [8, 7, 6, 5, 6, 6],
      notes: [
        'Operator Reink Media Group, LLC (Michigan AS, didirikan 2009) diungkapkan. Perusahaan ini juga merupakan Certified B Corporation yang diverifikasi pihak ketiga.',
        'Halaman khusus "How We Calculate Forex Broker Trust" menjelaskan elemen-elemen perhitungan skor kepercayaan.',
        'Sertifikasi B Corp menunjukkan komitmen tertentu terhadap kepentingan publik, tetapi dalam investigasi ini tidak ditemukan halaman pengungkapan rinci mengenai pendapatan iklan.',
        'Ditemukan satu postingan di Trustpilot yang mempertanyakan "banyaknya iklan dan netralitas" (1 kasus, belum dapat dikatakan sebagai pola).',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini.',
        'Tidak ditemukan kontroversi besar dalam cakupan investigasi kali ini.',
      ],
      sources: [
        { label: 'ForexBrokers.com — About Us', url: 'https://www.forexbrokers.com/about' },
        { label: 'ForexBrokers.com — How We Calculate Forex Broker Trust', url: 'https://www.forexbrokers.com/trust-score' },
        { label: 'Reink Media Group — B Corporation profile', url: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/reink-media-group-llc/' },
      ],
    },
    brokerchooser: {
      caseNo: 'CASE No. 010',
      name: 'BrokerChooser',
      siteUrl: 'https://brokerchooser.com/',
      status: 'warn',
      statusLabel: 'Ada Kekhawatiran',
      scores: [8, 7, 5, 4, 6, 4],
      notes: [
        'Nama asli pendiri Tibor Bedő dan Gergely Ferencz Korpos, basis di Budapest Hungaria, diungkapkan.',
        'Halaman "methodology" dan "why trust us" menjelaskan proses penilaian.',
        'Memiliki halaman "Advertiser Disclosure", tetapi sebagian kritikus menunjukkan "penjelasan model pendapatan kurang memadai".',
        'Ditemukan beberapa postingan di Trustpilot yang menyatakan "pendapatan afiliasi terkait dengan urutan rekomendasi" dan "mengalami kerugian dengan broker yang direkomendasikan".',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini.',
        'Pola keluhan di Trustpilot di atas adalah kasus utama yang ditemukan. Belum ada liputan investigasi media besar yang dapat dikonfirmasi.',
      ],
      sources: [
        { label: 'BrokerChooser — Advertiser Disclosure', url: 'https://brokerchooser.com/advertiser-disclosure' },
        { label: 'BrokerChooser — Online broker review methodology', url: 'https://brokerchooser.com/methodology' },
        { label: 'Trustpilot — BrokerChooser reviews', url: 'https://www.trustpilot.com/review/brokerchooser.com' },
      ],
    },
    brokersview: {
      caseNo: 'CASE No. 011',
      name: 'BrokersView',
      siteUrl: 'https://www.brokersview.com/',
      jpSupport: true,
      status: 'critical',
      statusLabel: 'Perlu Diwaspadai',
      scores: [2, 3, 2, 2, 4, 2],
      notes: [
        'Situs resmi sendiri mengakui "lokasi kantor tidak diungkapkan". Tahun pendirian juga berbeda-beda antar sumber (2017 vs 2022).',
        'Ada konten seperti "laporan mingguan broker curang", tetapi metode perhitungan skor yang konkret tidak dapat dikonfirmasi.',
        'Tidak ditemukan pengungkapan terkait iklan atau model pendapatan.',
        'Beberapa pengguna melaporkan tuduhan "tidak menghapus ulasan negatif meski sudah dibayar" dan "ada ulasan yang direkayasa". Skor Trustpilot keseluruhan juga rendah, 1,5.',
        'Dalam investigasi kali ini, tidak dapat dikonfirmasi kasus ketidaksesuaian langsung dengan data regulator.',
        'Ditemukan beberapa tuduhan dari pengguna bahwa situs ini "menerima uang dari broker untuk menjelekkan pesaing". Pola yang mirip dengan WikiFX disebutkan.',
      ],
      sources: [
        { label: 'Trustpilot — BrokersView reviews', url: 'https://www.trustpilot.com/review/www.brokersview.com' },
        { label: 'BrokersView — About Us', url: 'https://www.brokersview.com/about-us' },
        { label: 'Finance Scam — BrokersView: A Critical Review', url: 'https://www.financescam.com/2024/12/19/brokersview-a-critical-review/' },
      ],
    },
    forexbrokerrating: {
      caseNo: 'CASE No. 012',
      name: 'Forex-Broker-Rating.com',
      siteUrl: 'https://www.forex-broker-rating.com/',
      status: 'critical',
      statusLabel: 'Perlu Diwaspadai',
      scores: [2, 3, 2, 4, 5, 5],
      notes: [
        'Situs resmi hanya mencantumkan keterangan hak cipta "© 2009-2026 Forex Broker Rating.com" tanpa nama perusahaan operator atau alamat.',
        'Format penilaian berupa pendaftaran mandiri broker dan voting pengguna (berdasarkan informasi umum industri). Rumus penilaian yang konkret tidak dapat dikonfirmasi.',
        'Tidak ditemukan pengungkapan terkait iklan atau model pendapatan.',
        'Format pendaftaran mandiri plus voting secara struktural berisiko terhadap voting palsu, tetapi dalam investigasi kali ini tidak ditemukan kasus kecurangan konkret.',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini (penilaian bersifat sementara).',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah spesifik (perlu dicatat bahwa informasi situs itu sendiri sedikit, membatasi cakupan investigasi).',
      ],
      sources: [
        { label: 'Forex-Broker-Rating.com (versi bahasa Rusia)', url: 'https://www.forex-broker-rating.com/ru' },
      ],
    },
    daman: {
      caseNo: 'CASE No. 013',
      name: 'Daman（ضمان）',
      siteUrl: 'https://daman.reviews/',
      status: 'critical',
      statusLabel: 'Perlu Diwaspadai',
      scores: [2, 3, 2, 5, 5, 5],
      notes: [
        'Situs resmi tidak mencantumkan nama perusahaan operator, alamat, atau perwakilan — hanya alamat email yang dapat dikonfirmasi.',
        'Ada tautan menuju halaman yang setara dengan "kebijakan penilaian", tetapi detail isinya tidak dapat dikonfirmasi.',
        'Tidak ditemukan pengungkapan terkait iklan atau model pendapatan.',
        'Tidak ditemukan informasi kuat terkait keaslian ulasan dalam investigasi kali ini (penilaian bersifat sementara karena informasi situs sendiri sedikit).',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini (penilaian bersifat sementara).',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah spesifik (perlu dicatat bahwa ini situs kecil berbahasa Arab sehingga cakupan investigasi terbatas).',
      ],
      sources: [
        { label: 'Daman — Daftar ulasan broker', url: 'https://daman.reviews/forex-brokers' },
      ],
    },
    seputarforex: {
      caseNo: 'CASE No. 014',
      name: 'Seputar Forex',
      siteUrl: 'https://www.seputarforex.net/',
      status: 'warn',
      statusLabel: 'Ada Kekhawatiran',
      scores: [4, 4, 4, 5, 6, 5],
      notes: [
        'Halaman informasi operator di situs resmi tidak dapat diakses langsung (tautan rusak), sehingga nama perusahaan operator dan perwakilan tidak dapat dikonfirmasi.',
        'Pengungkapan metode penilaian dan logika penilaian yang konkret tidak dapat dikonfirmasi dalam investigasi kali ini.',
        'Pengungkapan eksplisit terkait iklan atau model pendapatan tidak dapat dikonfirmasi.',
        'Tidak ditemukan informasi kuat terkait keaslian ulasan dalam investigasi kali ini (cakupan pencarian berbahasa Inggris terbatas karena informasi berbahasa Indonesia).',
        'Termasuknya broker yang terdaftar di regulator resmi setempat (Bappebti) dalam cakupan situs merupakan faktor yang cukup positif dari sisi konsistensi dengan informasi regulasi.',
        'Dalam cakupan investigasi kali ini, tidak ditemukan kasus masalah spesifik (perlu dicatat keterbatasan cakupan seperti disebut di atas).',
      ],
      sources: [
        { label: 'Seputar Forex — Daftar ulasan broker', url: 'https://www.seputarforex.net/broker/forex/review' },
      ],
    },
    fxscouts: {
      caseNo: 'CASE No. 015',
      name: 'FX Scouts',
      siteUrl: 'https://fxscouts.com/',
      jpSupport: true,
      status: 'good',
      statusLabel: 'Baik',
      scores: [7, 6, 6, 6, 6, 6],
      notes: [
        'Operator FxScouts Group AB (terdaftar di Swedia, didirikan 2011) dicantumkan di situs resmi.',
        'Mempublikasikan kerangka kerja "Broker Score" dan "Trust Rating". Proses verifikasi juga dijelaskan untuk penilaian prop firm.',
        'Menyatakan sendiri "beroperasi hanya dari pendapatan afiliasi dan mengungkapkan hubungan tersebut secara jelas".',
        'Ditemukan satu artikel pihak ketiga yang mengklaim situs ini "situs penipuan", tetapi karena kredibilitas sumbernya rendah dan kurang didukung bukti, tidak dinyatakan sebagai fakta.',
        'Tidak ditemukan kasus ketidaksesuaian yang jelas dengan data regulator dalam investigasi kali ini.',
        'Selain satu artikel kritik yang belum terverifikasi di atas, tidak ditemukan kontroversi besar.',
      ],
      sources: [
        { label: 'FxScouts — About Us', url: 'https://fxscouts.com/about-us/' },
      ],
    },
  };

  const AUDIT_DATE = '2026-09-18'; // Tanggal investigasi serentak kali ini (situs yang diinvestigasi ulang akan mendapat tambahan history di SITE_DATA)
