  const AXES6 = ['Transparence', 'Logique', 'Revenus', 'Authenticité', 'Conformité', 'Antécédents'];
  const AXIS_FULL_NAMES = ["Transparence des informations sur l'exploitant", "Publicité de la logique d'évaluation", 'Divulgation du modèle de revenus', 'Mesures contre les faux avis', 'Cohérence avec les données des autorités de régulation', 'Antécédents de problèmes'];

  // ---------- Données des dossiers audités (l'ordre des axes correspond à AXES6/AXIS_FULL_NAMES) ----------
  const SITE_DATA = {
    wikifx: {
      caseNo: 'CASE No. 001',
      name: 'WikiFX',
      siteUrl: 'https://www.wikifx.com/',
      status: 'unrecommended',
      statusLabel: 'Déconseillé',
      scores: [1, 3, 1, 2, 1, 1],
      notes: [
        "La page « À propos » du site officiel ne mentionne ni raison sociale, ni adresse, ni dirigeant (seules des coordonnées de contact sont indiquées). La Securities and Futures Commission de Hong Kong (SFC) a officiellement averti que « l'adresse à Hong Kong revendiquée par la société n'existe pas, et qu'elle est soupçonnée d'utiliser sans autorisation les informations d'une entreprise légitime ».",
        "Le cadre des 5 indicateurs « License/Regulation/Risk Control/Business/Software » est rendu public. En revanche, la méthode de calcul détaillée n'est pas divulguée, et plusieurs articles soulignent qu'« aucune explication n'est fournie même sur demande ».",
        "Aucune divulgation du modèle de revenus n'apparaît sur le site. Selon des documents internes obtenus par l'enquête de DL News, la société aurait exigé jusqu'à 128 000 $ auprès de courtiers, attribuant une note élevée en cas de paiement et une note basse en cas de refus (la société dément).",
        "De nombreux signalements indiquent que des avis non vérifiés sont publiés tels quels. La note sur Trustpilot est également qualifiée de « Poor » (médiocre), 2/5.",
        "De nombreux cas ont été signalés où des courtiers dûment agréés par la FCA, la CySEC, etc. sont faussement présentés comme « non enregistrés » ou « suspects ». De plus, l'adresse d'enregistrement de la société elle-même a été qualifiée d'« inexistante » par la SFC de Hong Kong.",
        "Plusieurs sources indépendantes existent : l'enquête de DL News, l'avertissement officiel de la SFC de Hong Kong, des articles faisant état de soupçons similaires concernant le site sœur WikiBit, ainsi que des accusations publiques émanant de plusieurs courtiers.",
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Finance Magnates — Hong Kong SFC warns of WikiFX', url: 'https://www.financemagnates.com/forex/hong-kong-continues-to-scrutinize-fx-space-warns-of-wikifx/' },
        { label: 'Trustpilot — WikiFX reviews', url: 'https://www.trustpilot.com/review/wikifx.com' },
        { label: 'Site officiel de WikiFX — page « À propos »', url: 'https://www.wikifx.com/en/about.html' },
        { label: 'Déclaration de démenti de WikiFX (Medium)', url: 'https://wikifxcom.medium.com/wikifx-denies-they-take-money-from-brokers-for-positive-rankings-d1f1ac40fc79' },
      ],
    },
    wikibit: {
      caseNo: 'CASE No. 002',
      name: 'WikiBit',
      siteUrl: 'https://www.wikibit.com/',
      status: 'critical',
      statusLabel: 'Vigilance requise',
      scores: [4, 3, 1, 5, 1, 2],
      notes: [
        "La page « À propos » mentionne la raison sociale de l'exploitant, « COOLBIT CO., LIMITED », mais ni l'adresse ni le nom du dirigeant n'y figurent. La divulgation est plus poussée que chez WikiFX, mais reste insuffisante.",
        "Le cadre d'un « modèle de notation du risque à 5 dimensions » est publié, mais aucune explication concrète sur la méthode de calcul ni sur la pondération n'a été trouvée.",
        "Aucune divulgation du modèle de revenus n'apparaît sur le site. Le site fait l'objet de la même enquête (DL News) que le site sœur WikiFX.",
        "Le nombre d'avis sur Trustpilot reste faible (5 avis, moyenne de 3,1/5), et aucun élément solide concernant l'authenticité des avis n'a été trouvé lors de cette enquête.",
        "L'enquête de DL News a nommément rapporté que le site « attribue une note élevée à des plateformes d'échange de cryptomonnaies visées par des préoccupations des régulateurs » et « présente la situation réglementaire d'entreprises annonceuses de façon plus favorable que la réalité ».",
        "Outre l'enquête de DL News (mentionnée dans le même article que WikiFX), des plaintes concernant des litiges financiers ont été constatées sur Trustpilot. Le nombre de sources indépendantes est toutefois moins élevé que pour WikiFX.",
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Trustpilot — WikiBit reviews', url: 'https://www.trustpilot.com/review/wikibit.com' },
        { label: 'Site officiel de WikiBit — About', url: 'https://www.wikibit.com/about' },
      ],
    },
    fpa: {
      caseNo: 'CASE No. 003',
      name: 'Forex Peace Army',
      siteUrl: 'https://www.forexpeacearmy.com/',
      status: 'warn',
      statusLabel: 'Réserves partielles',
      scores: [7, 6, 6, 4, 6, 4],
      notes: [
        'Il est publiquement établi que la société a été fondée en 2005 par Dmitri Chavkerov, avec un siège basé à New York, aux États-Unis. Contrairement à WikiFX/WikiBit, la personne physique dirigeant le site peut être identifiée nommément.',
        "Le site publie un processus d'examen des avis par des modérateurs humains, une vérification des faits auprès des courtiers, ainsi qu'un mécanisme de résolution entre parties appelé « FPA Traders Court ». La formule de calcul chiffrée elle-même n'est toutefois pas divulguée.",
        "Le site indique explicitement qu'il « perçoit des revenus publicitaires, sans que cela ne constitue une recommandation des produits annoncés ». Cette divulgation est relativement soignée pour le secteur. Des articles indépendants et des utilisateurs signalent toutefois régulièrement un favoritisme envers les courtiers annonceurs.",
        "La modération humaine et le processus de vérification auprès des courtiers vont plus loin que sur d'autres sites, mais les critiques dénonçant un favoritisme envers les annonceurs sont nombreuses, et la note sur Trustpilot est également qualifiée de « Bad » (mauvaise), 1,2/5.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données publiées par les autorités de régulation (évaluation provisoire, une vérification exhaustive n'ayant pas été réalisée).",
        'Finance Magnates a enquêté sur le fonctionnement réel du site dans un article intitulé « Bullets and Bribes ». Les litiges pour diffamation liés au contenu publié sont nombreux, au point que plusieurs services juridiques spécialisés dans la suppression d\'avis se sont développés autour de ce contentieux.',
      ],
      sources: [
        { label: 'Finance Magnates — Bullets and Bribes: A Look into the World of the Forex Peace Army', url: 'https://www.financemagnates.com/executives/interview/bullets-and-bribes-a-look-into-the-world-of-the-forex-peace-army/' },
        { label: 'Forex Peace Army — page publicitaire (modèle de revenus)', url: 'https://www.forexpeacearmy.com/ad' },
        { label: 'Trustpilot — Forex Peace Army reviews', url: 'https://www.trustpilot.com/review/www.forexpeacearmy.com' },
        { label: "Lawyerd — analyse juridique sur la suppression d'avis FPA", url: 'https://lawyerd.net/blog/forex-peace-army-review-removal/' },
      ],
    },
    dailyforex: {
      caseNo: 'CASE No. 004',
      name: 'DailyForex',
      siteUrl: 'https://www.dailyforex.com/',
      status: 'good',
      statusLabel: 'Satisfaisant',
      scores: [7, 7, 7, 5, 6, 7],
      notes: [
        "Le site officiel indique l'adresse de l'exploitant, Global On Media (Delaware, États-Unis). Fondée en 2008, l'entreprise divulgue également sa taille, avec environ 19 employés.",
        'Le site publie des pages dédiées « Our Methodology » et « Why You Can Trust Us », précisant que la réglementation et la sécurité sont considérées comme prioritaires.',
        "Le site dispose d'une page de divulgation précisant que « des revenus publicitaires existent, mais les considérations commerciales n'influencent pas l'évaluation des courtiers ». Les partenariats d'affiliation sont également divulgués.",
        "Les avis sur Trustpilot restent peu nombreux (3 avis), et aucun élément solide concernant l'authenticité des avis n'a été trouvé lors de cette enquête.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation (vérification exhaustive non réalisée).",
        "Dans le cadre de cette enquête, aucun problème grave concret, tel qu'un litige judiciaire ou une sanction administrative, n'a été identifié.",
      ],
      sources: [
        { label: 'DailyForex — About Us', url: 'https://www.dailyforex.com/aboutus' },
        { label: 'DailyForex — Our Methodology', url: 'https://www.dailyforex.com/our-methodology' },
        { label: 'DailyForex — Why You Can Trust Our Content', url: 'https://www.dailyforex.com/why-trust-us' },
        { label: 'Trustpilot — DailyForex reviews', url: 'https://www.trustpilot.com/review/dailyforex.com' },
      ],
    },
    tradersunion: {
      caseNo: 'CASE No. 005',
      name: 'Traders Union',
      siteUrl: 'https://tradersunion.com/',
      status: 'warn',
      statusLabel: 'Réserves partielles',
      scores: [5, 6, 6, 3, 6, 4],
      notes: [
        'Le siège est déclaré à Limassol, à Chypre, mais le nom du fondateur ou du dirigeant n\'a pas pu être vérifié.',
        'Le site publie un cadre combinant plusieurs indicateurs, notamment le User Reviews Score, le Loyalty Index, le Popularity Score et le Web Mention Index.',
        "Le site indique percevoir des revenus via la publicité et un programme de partenariat, tout en affirmant que « la rédaction n'a pas accès aux données des annonceurs ».",
        "Le site publie lui-même une page de « politique de lutte contre les faux avis », mais plusieurs signalements sur Trustpilot dénoncent un favoritisme envers les annonceurs. La communauté de Forex Peace Army fait par ailleurs état d'une accusation selon laquelle le site aurait menacé de publier un avis négatif en l'absence de paiement (à noter qu'il s'agit d'une allégation émanant d'un tiers, non vérifiée).",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation (vérification exhaustive non réalisée).",
        "L'allégation de menace évoquée ci-dessus au sein de la communauté FPA constitue le principal cas relevé. Aucune reconnaissance officielle par une autorité publique ni enquête menée par un grand média n'a pu être confirmée.",
      ],
      sources: [
        { label: 'Traders Union — Combating Fake Reviews Policy', url: 'https://tradersunion.com/combating-fake-reviews/' },
        { label: 'Trustpilot — Traders Union reviews', url: 'https://www.trustpilot.com/review/tradersunion.com' },
        { label: 'Forex Peace Army — Traders Union review thread', url: 'https://www.forexpeacearmy.com/forex-reviews/8243/www.tradersunion.com' },
      ],
    },
    forexratings: {
      caseNo: 'CASE No. 006',
      name: 'Forex-Ratings.com',
      siteUrl: 'https://www.forex-ratings.com/',
      status: 'critical',
      statusLabel: 'Vigilance requise',
      scores: [2, 4, 2, 5, 5, 5],
      notes: [
        'La page officielle « À propos » ne mentionne ni raison sociale, ni adresse, ni dirigeant ; seul un lien « Contact us » est proposé.',
        "Une explication de principe indique que le site « intègre un mécanisme de vote reflétant l'évolution de la popularité des courtiers sur différentes périodes », mais la formule de calcul concrète n'est pas divulguée.",
        'Aucune divulgation relative à la publicité ou au parrainage n\'a été trouvée.',
        "Cette enquête n'a trouvé aucun élément solide concernant l'authenticité des avis (évaluation provisoire).",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation (évaluation provisoire).",
        "Aucun problème concret n'a été identifié dans le cadre de cette enquête (évaluation provisoire ; le manque de transparence sur l'exploitant constitue en soi un facteur de risque).",
      ],
      sources: [
        { label: 'Forex-Ratings.com — About Forex Ratings', url: 'https://www.forex-ratings.com/company/about-forex-ratings/' },
      ],
    },
    fxtrustscore: {
      caseNo: 'CASE No. 007',
      name: 'FX Trust Score',
      siteUrl: 'https://www.fxtrustscore.com/',
      status: 'good',
      statusLabel: 'Satisfaisant',
      scores: [8, 7, 7, 6, 6, 6],
      notes: [
        'Le site officiel précise la société exploitante, Cheyne Media Ltd (enregistrée à Gibraltar, numéro d\'enregistrement 122915), ainsi que le parcours de la fondatrice, Anthea Michael. Le niveau de divulgation figure parmi les plus élevés de cette enquête.',
        "Le site calcule ses notes selon une méthode publique propre et dispose d'une page de politique précisant que « la note ne varie pas en fonction d'un paiement ou d'un partenariat ».",
        "Le site dispose d'une page dédiée divulguant ses relations publicitaires et d'affiliation, tout en précisant qu'elles sont séparées du système de notation.",
        'Le niveau de divulgation est élevé, mais le site étant relativement récent, les cas de vérification indépendante par des tiers restent encore peu nombreux.',
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation.",
        "Aucun problème concret n'a été identifié dans le cadre de cette enquête (à noter que le site étant récent, les cas de vérification publique restent eux-mêmes peu nombreux).",
      ],
      sources: [
        { label: 'FX Trust Score — About Us', url: 'https://www.fxtrustscore.com/about-us/' },
        { label: 'FX Trust Score — Disclosures', url: 'https://www.fxtrustscore.com/disclosures/' },
      ],
    },
    compareforexbrokers: {
      caseNo: 'CASE No. 008',
      name: 'CompareForexBrokers',
      siteUrl: 'https://www.compareforexbrokers.com/',
      status: 'good',
      statusLabel: 'Satisfaisant',
      scores: [9, 7, 8, 6, 6, 7],
      notes: [
        'Le site publie les noms des fondateurs, Justin Grossbard et Noam Korbl, son siège à Melbourne en Australie, ainsi que son numéro d\'enregistrement ABN. Il s\'agit du niveau de divulgation le plus élevé de cette enquête.',
        "La page « Our Methodology » explique de façon concrète les éléments pris en compte dans l'évaluation.",
        "Une page dédiée « Advertiser Disclosure » explique le mécanisme des commissions de partenariat et la séparation organisationnelle selon laquelle « l'équipe de rédaction et de recherche ignore quels courtiers versent des commissions ».",
        "Le site affiche plus de 37 avis sur Trustpilot avec une note de 4/5, ce qui constitue un historique établi. Aucun problème sérieux d'authenticité n'a été identifié lors de cette enquête.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation.",
        "Aucune controverse majeure n'a été confirmée dans le cadre de cette enquête.",
      ],
      sources: [
        { label: 'CompareForexBrokers — About Us', url: 'https://www.compareforexbrokers.com/about-us/' },
        { label: 'CompareForexBrokers — Advertiser Disclosure', url: 'https://www.compareforexbrokers.com/about-us/advertiser-disclosure/' },
        { label: 'CompareForexBrokers — Our Methodology', url: 'https://www.compareforexbrokers.com/our-methodology/' },
      ],
    },
    forexbrokerscom: {
      caseNo: 'CASE No. 009',
      name: 'ForexBrokers.com',
      siteUrl: 'https://www.forexbrokers.com/',
      status: 'good',
      statusLabel: 'Satisfaisant',
      scores: [8, 7, 6, 5, 6, 6],
      notes: [
        "L'exploitant, Reink Media Group, LLC (Michigan, États-Unis, fondée en 2009), est rendu public. La société est également certifiée B Corporation par un organisme tiers.",
        'Une page dédiée intitulée « How We Calculate Forex Broker Trust » explique les éléments entrant dans le calcul du score de confiance.',
        "La certification B Corp témoigne d'un certain engagement d'intérêt général, mais cette enquête n'a pas permis de trouver de page détaillant précisément les revenus publicitaires.",
        "Un avis sur Trustpilot évoque « la quantité de publicités et des doutes sur la neutralité » du site (un seul cas, insuffisant pour établir une tendance).",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation.",
        "Aucune controverse majeure n'a été confirmée dans le cadre de cette enquête.",
      ],
      sources: [
        { label: 'ForexBrokers.com — About Us', url: 'https://www.forexbrokers.com/about' },
        { label: 'ForexBrokers.com — How We Calculate Forex Broker Trust', url: 'https://www.forexbrokers.com/trust-score' },
        { label: 'Reink Media Group — B Corporation profile', url: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/reink-media-group-llc/' },
      ],
    },
    brokerchooser: {
      caseNo: 'CASE No. 010',
      name: 'BrokerChooser',
      siteUrl: 'https://brokerchooser.com/',
      status: 'warn',
      statusLabel: 'Réserves partielles',
      scores: [8, 7, 5, 4, 6, 4],
      notes: [
        'Le site publie les noms des fondateurs, Tibor Bedő et Gergely Ferencz Korpos, ainsi que son siège à Budapest, en Hongrie.',
        'Les pages « methodology » et « why trust us » expliquent le processus d\'évaluation.',
        'Le site dispose d\'une page « Advertiser Disclosure », mais certains critiques estiment que l\'explication du modèle de revenus reste insuffisante.',
        "Plusieurs avis sur Trustpilot affirment que « les revenus d'affiliation sont liés au classement des recommandations » et font état de pertes subies avec des courtiers recommandés.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation.",
        "Le principal élément relevé est le schéma de plaintes observé sur Trustpilot évoqué ci-dessus. Aucune enquête menée par un grand média n'a pu être confirmée.",
      ],
      sources: [
        { label: 'BrokerChooser — Advertiser Disclosure', url: 'https://brokerchooser.com/advertiser-disclosure' },
        { label: 'BrokerChooser — Online broker review methodology', url: 'https://brokerchooser.com/methodology' },
        { label: 'Trustpilot — BrokerChooser reviews', url: 'https://www.trustpilot.com/review/brokerchooser.com' },
      ],
    },
    brokersview: {
      caseNo: 'CASE No. 011',
      name: 'BrokersView',
      siteUrl: 'https://www.brokersview.com/',
      status: 'critical',
      statusLabel: 'Vigilance requise',
      scores: [2, 3, 2, 2, 4, 2],
      notes: [
        "Le site officiel reconnaît lui-même que « l'adresse du bureau n'est pas divulguée ». L'année de fondation varie également selon les sources, entre 2017 et 2022.",
        "Le site publie des contenus tels qu'un « rapport hebdomadaire sur les courtiers frauduleux », mais aucune méthode concrète de calcul des notes n'a pu être vérifiée.",
        "Aucune divulgation relative à la publicité ou au modèle de revenus n'a été trouvée.",
        "Plusieurs utilisateurs rapportent des allégations selon lesquelles « le paiement ne garantit pas la suppression d'un avis négatif » et selon lesquelles « certains avis seraient fabriqués ». La note globale sur Trustpilot est également basse, à 1,5.",
        "Cette enquête n'a pas permis de confirmer de divergence directe avec les données des autorités de régulation.",
        "Plusieurs utilisateurs dénoncent le fait que le site « recevrait de l'argent de courtiers pour dénigrer leurs concurrents ». Un schéma similaire à celui de WikiFX est pointé du doigt.",
      ],
      sources: [
        { label: 'Trustpilot — BrokersView reviews', url: 'https://www.trustpilot.com/review/www.brokersview.com' },
        { label: 'BrokersView — About Us', url: 'https://www.brokersview.com/about-us' },
        { label: 'Finance Scam — BrokersView: A Critical Review', url: 'https://www.financescam.com/2024/12/19/brokersview-a-critical-review/' },
      ],
    },
    forexbrokerrating: {
      caseNo: 'CASE No. 012',
      name: 'Forex-Broker-Rating.com',
      siteUrl: 'https://www.forex-broker-rating.com/',
      status: 'critical',
      statusLabel: 'Vigilance requise',
      scores: [2, 3, 2, 4, 5, 5],
      notes: [
        'Le site officiel ne comporte qu\'une mention de copyright « © 2009-2026 Forex Broker Rating.com », sans aucune indication de raison sociale ni d\'adresse.',
        "Le format d'évaluation repose sur l'auto-inscription des courtiers et le vote des utilisateurs (information générale du secteur). Aucune formule de notation concrète n'a pu être vérifiée.",
        "Aucune divulgation relative à la publicité ou au modèle de revenus n'a été trouvée.",
        "Le format combinant auto-inscription et vote comporte structurellement un risque de votes usurpés, mais aucun cas concret de fraude n'a été confirmé lors de cette enquête.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation (évaluation provisoire).",
        "Aucun problème concret n'a été identifié dans le cadre de cette enquête (à noter que le site propose peu d'informations, ce qui limite l'exhaustivité de l'investigation).",
      ],
      sources: [
        { label: 'Forex-Broker-Rating.com (version russe)', url: 'https://www.forex-broker-rating.com/ru' },
      ],
    },
    daman: {
      caseNo: 'CASE No. 013',
      name: 'Daman（ضمان）',
      siteUrl: 'https://daman.reviews/',
      status: 'critical',
      statusLabel: 'Vigilance requise',
      scores: [2, 3, 2, 5, 5, 5],
      notes: [
        'Le site officiel ne mentionne ni raison sociale, ni adresse, ni dirigeant ; seule une adresse e-mail a pu être vérifiée.',
        'Un lien vers une page correspondant à une « politique d\'évaluation » existe, mais le détail de son contenu n\'a pas pu être vérifié.',
        "Aucune divulgation relative à la publicité ou au modèle de revenus n'a été trouvée.",
        "Cette enquête n'a trouvé aucun élément solide concernant l'authenticité des avis (évaluation provisoire en raison du faible volume d'informations disponibles sur le site).",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation (évaluation provisoire).",
        "Aucun problème concret n'a été identifié dans le cadre de cette enquête (à noter que, s'agissant d'un petit site arabophone, l'exhaustivité de l'investigation est limitée).",
      ],
      sources: [
        { label: 'Daman — liste des avis sur les courtiers', url: 'https://daman.reviews/forex-brokers' },
      ],
    },
    seputarforex: {
      caseNo: 'CASE No. 014',
      name: 'Seputar Forex',
      siteUrl: 'https://www.seputarforex.net/',
      status: 'warn',
      statusLabel: 'Réserves partielles',
      scores: [4, 4, 4, 5, 6, 5],
      notes: [
        "La page d'informations sur l'exploitant du site officiel était inaccessible (lien rompu), empêchant de vérifier la raison sociale ou le dirigeant.",
        "Aucune publication d'une méthode de notation ou d'une logique d'évaluation concrète n'a été trouvée lors de cette enquête.",
        'Aucune divulgation explicite relative à la publicité ou au modèle de revenus n\'a été constatée.',
        "Cette enquête n'a trouvé aucun élément solide concernant l'authenticité des avis (les informations étant en indonésien, l'exhaustivité des recherches en anglais reste limitée).",
        "Le fait d'inclure des courtiers enregistrés auprès de l'autorité locale compétente (Bappebti) constitue un élément plutôt positif du point de vue de la cohérence avec les données réglementaires.",
        "Aucun problème concret n'a été identifié dans le cadre de cette enquête (les mêmes limites d'exhaustivité mentionnées ci-dessus s'appliquent).",
      ],
      sources: [
        { label: 'Seputar Forex — liste des avis sur les courtiers', url: 'https://www.seputarforex.net/broker/forex/review' },
      ],
    },
    fxscouts: {
      caseNo: 'CASE No. 015',
      name: 'FX Scouts',
      siteUrl: 'https://fxscouts.com/',
      status: 'good',
      statusLabel: 'Satisfaisant',
      scores: [7, 6, 6, 6, 6, 6],
      notes: [
        "Le site officiel indique l'exploitant, FxScouts Group AB (enregistrée en Suède, fondée en 2011).",
        'Le site publie les cadres « Broker Score » et « Trust Rating ». Pour l\'évaluation des prop firms, le processus de vérification est également expliqué.',
        "Le site indique lui-même « fonctionner uniquement grâce aux revenus d'affiliation, dont la relation est clairement divulguée ».",
        "Un article tiers affirmant qu'il s'agirait d'« un site frauduleux » a été trouvé, mais la fiabilité de la source étant faible et les preuves insuffisantes, ce fait n'est pas retenu comme avéré.",
        "Cette enquête n'a pas permis de confirmer de divergence manifeste avec les données des autorités de régulation.",
        "À l'exception de l'article critique non vérifié mentionné ci-dessus, aucune controverse majeure n'a été confirmée.",
      ],
      sources: [
        { label: 'FxScouts — About Us', url: 'https://fxscouts.com/about-us/' },
      ],
    },
  };

  const AUDIT_DATE = '2026-09-18'; // Date de l'audit initial (les sites ayant fait l'objet d'une nouvelle enquête auront un champ history ajouté dans SITE_DATA)
