  const AXES6 = ['透明度', '逻辑公开', '收益披露', '真实性对策', '监管一致性', '过往案例'];
  const AXIS_FULL_NAMES = ['运营者信息的透明度', '评价逻辑的公开程度', '收益模式的披露', '评论真实性对策', '与监管机构数据的一致性', '过往问题案例'];

  // ---------- 已调查案件数据（各轴顺序与AXES6/AXIS_FULL_NAMES一致） ----------
  const SITE_DATA = {
    wikifx: {
      caseNo: 'CASE No. 001',
      name: 'WikiFX',
      status: 'unrecommended',
      statusLabel: '不推荐',
      scores: [1, 3, 1, 2, 1, 1],
      notes: [
        '官方网站的公司简介页面未列出公司名称、所在地及代表人姓名（仅有联系方式）。香港证券及期货事务监察委员会（SFC）已发出正式警告，指出"该公司所称的香港地址并不存在，涉嫌未经授权使用正规企业的信息"。',
        '公开了"License/Regulation/Risk Control/Business/Software"（牌照/监管/风控/业务/软件）五项指标的框架，但详细的计算方法未公开，多篇报道指出"即使询问也得不到说明"。',
        '网站上完全没有披露收益模式。据调查报道媒体DL News获得的内部资料显示，该公司被曝向经纪商索要最高12.8万美元，支付则给予高评分、拒绝则给予低评分（该公司对此予以否认）。',
        '有大量报告指出未经核实的投稿会被直接采纳反映。Trustpilot上的评分也为"差"2/5。',
        '有大量报告指出该网站将持有FCA、CySEC等正规牌照的经纪商错误标注为"未注册""可疑"。此外，其自身的注册地址也被香港SFC指出"并不存在"。',
        'DL News的调查报道、香港SFC的官方警告、姊妹网站WikiBit也因同类嫌疑被报道，以及多家经纪商的公开指控——存在多个相互独立的依据。',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Finance Magnates — Hong Kong SFC warns of WikiFX', url: 'https://www.financemagnates.com/forex/hong-kong-continues-to-scrutinize-fx-space-warns-of-wikifx/' },
        { label: 'Trustpilot — WikiFX reviews', url: 'https://www.trustpilot.com/review/wikifx.com' },
        { label: 'WikiFX官方网站 — 公司简介页面', url: 'https://www.wikifx.com/en/about.html' },
        { label: 'WikiFX的否认声明（Medium）', url: 'https://wikifxcom.medium.com/wikifx-denies-they-take-money-from-brokers-for-positive-rankings-d1f1ac40fc79' },
      ],
    },
    wikibit: {
      caseNo: 'CASE No. 002',
      name: 'WikiBit',
      status: 'critical',
      statusLabel: '需警惕',
      scores: [4, 3, 1, 5, 1, 2],
      notes: [
        '公司简介页面记载了运营公司名称"COOLBIT CO., LIMITED"，但未记载所在地及代表人姓名。披露程度虽高于WikiFX，但仍不充分。',
        '公开了"五方面风险评分模型"的框架，但未见具体计算方法及权重的说明。',
        '网站上完全没有披露收益模式。与姊妹网站WikiFX同样成为DL News同一调查报道的对象。',
        'Trustpilot上的评论数量尚少（5条，平均3.1/5），本次调查未发现能作为评论真实性有力依据的报告。',
        'DL News的调查报道点名指出该网站"给被监管机构提出疑虑的加密货币交易所打出高分""将广告主企业的监管状况美化得比实际情况更好"。',
        '除DL News的调查报道（在与WikiFX相同的文章中提及）外，Trustpilot上也可确认到关于资金纠纷的投诉帖。独立依据的数量不及WikiFX多。',
      ],
      sources: [
        { label: "DL News — Asian review site draws fire for 'making scam brokers look legit'", url: 'https://www.dlnews.com/articles/markets/controversial-asian-broker-review-site-moves-into-crypto/' },
        { label: 'Trustpilot — WikiBit reviews', url: 'https://www.trustpilot.com/review/wikibit.com' },
        { label: 'WikiBit官方网站 — About', url: 'https://www.wikibit.com/about' },
      ],
    },
    fpa: {
      caseNo: 'CASE No. 003',
      name: 'Forex Peace Army',
      status: 'warn',
      statusLabel: '部分存疑',
      scores: [7, 6, 6, 4, 6, 4],
      notes: [
        '公开信息显示该网站由Dmitri Chavkerov于2005年创立，总部明确标注为美国纽约。与WikiFX/WikiBit不同，可以通过实名确定运营者个人身份。',
        '公开了人工评论审核、向经纪商核实事实，以及名为"FPA Traders Court"的当事人纠纷调解流程。但具体的数值化计算公式本身并未公开。',
        '官网上明确写明"通过展示广告获得收益，但这并不代表推荐相关广告产品"。就披露程度而言在业界内属于较为详尽的一类。但独立报道及用户屡次指出投放广告的经纪商受到优待。',
        '实施人工审核及向经纪商核实的流程，这一点比其他网站更为深入，但关于偏袒广告主的批评较多，Trustpilot上的评分也为"差"1.2/5。',
        '本次调查未能确认与监管机构公开数据存在明确不一致的案例（由于未进行全面核查，属于暂定评价）。',
        'Finance Magnates曾以题为"Bullets and Bribes"的调查报道采访其运营实况。围绕刊载内容的诽谤纠纷较多，甚至存在多家专门代理删帖业务的法律服务机构，可见争议之激烈。',
      ],
      sources: [
        { label: 'Finance Magnates — Bullets and Bribes: A Look into the World of the Forex Peace Army', url: 'https://www.financemagnates.com/executives/interview/bullets-and-bribes-a-look-into-the-world-of-the-forex-peace-army/' },
        { label: 'Forex Peace Army — 广告页面（收益模式）', url: 'https://www.forexpeacearmy.com/ad' },
        { label: 'Trustpilot — Forex Peace Army reviews', url: 'https://www.trustpilot.com/review/www.forexpeacearmy.com' },
        { label: 'Lawyerd — 关于FPA评论删除的法律解读', url: 'https://lawyerd.net/blog/forex-peace-army-review-removal/' },
      ],
    },
    dailyforex: {
      caseNo: 'CASE No. 004',
      name: 'DailyForex',
      status: 'good',
      statusLabel: '良好',
      scores: [7, 7, 7, 5, 6, 7],
      notes: [
        '官网明确标注运营方Global On Media的地址（美国特拉华州）。披露了2008年成立、员工约19人等规模信息。',
        '公开了"Our Methodology"与"Why You Can Trust Us"专页，明确表示将监管与安全性视为最重要因素。',
        '设有明确写明"虽有广告收入，但商业因素不会影响经纪商评价"的披露页面，同时披露了联盟营销合作关系。',
        'Trustpilot上的评论仅有3条，数量尚少，本次调查未发现能作为真实性有力依据的信息。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例（未进行全面核查）。',
        '在本次调查范围内，未发现具体的诉讼、行政处分等重大问题案例。',
      ],
      sources: [
        { label: 'DailyForex — About Us', url: 'https://www.dailyforex.com/aboutus' },
        { label: 'DailyForex — Our Methodology', url: 'https://www.dailyforex.com/our-methodology' },
        { label: 'DailyForex — Why You Can Trust Our Content', url: 'https://www.dailyforex.com/why-trust-us' },
        { label: 'Trustpilot — DailyForex reviews', url: 'https://www.trustpilot.com/review/dailyforex.com' },
      ],
    },
    tradersunion: {
      caseNo: 'CASE No. 005',
      name: 'Traders Union',
      status: 'warn',
      statusLabel: '部分存疑',
      scores: [5, 6, 6, 3, 6, 4],
      notes: [
        '公开信息显示总部位于塞浦路斯利马索尔，但未能确认创始人及代表人姓名。',
        '公开了结合User Reviews Score（用户评价分）、Loyalty Index（忠诚度指数）、Popularity Score（人气分）、Web Mention Index（网络提及指数）等多项指标的框架。',
        '明确写明通过广告及合作伙伴计划获得收益，并声称"撰稿团队不会接触广告主数据"。',
        '该网站自行公开了"打击虚假评论政策"页面，但Trustpilot上有多条指出其"偏袒广告主"的意见。此外，Forex Peace Army社区中也有指控称其"威胁称若不付款就发布负面评论"（需注意这是第三方提出、尚未经核实的指控）。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例（未进行全面核查）。',
        '上述FPA社区中的威胁嫌疑指控是主要案例。尚未确认存在官方机构认定或大型媒体调查报道。',
      ],
      sources: [
        { label: 'Traders Union — Combating Fake Reviews Policy', url: 'https://tradersunion.com/combating-fake-reviews/' },
        { label: 'Trustpilot — Traders Union reviews', url: 'https://www.trustpilot.com/review/tradersunion.com' },
        { label: 'Forex Peace Army — Traders Union review thread', url: 'https://www.forexpeacearmy.com/forex-reviews/8243/www.tradersunion.com' },
      ],
    },
    forexratings: {
      caseNo: 'CASE No. 006',
      name: 'Forex-Ratings.com',
      status: 'critical',
      statusLabel: '需警惕',
      scores: [2, 4, 2, 5, 5, 5],
      notes: [
        '官方公司简介页面未记载运营公司名称、所在地及代表人，仅有"Contact us"（联系我们）链接。',
        '有说明称"纳入投票机制，反映经纪商在多个时间段内人气变化"的方针介绍，但具体计算公式未公开。',
        '未见关于广告及赞助关系的披露。',
        '本次调查未发现能作为真实性有力依据的信息（暂定评价）。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例（暂定评价）。',
        '在本次调查范围内未发现具体问题案例（暂定评价。运营信息不透明本身即为风险因素）。',
      ],
      sources: [
        { label: 'Forex-Ratings.com — About Forex Ratings', url: 'https://www.forex-ratings.com/company/about-forex-ratings/' },
      ],
    },
    fxtrustscore: {
      caseNo: 'CASE No. 007',
      name: 'FX Trust Score',
      status: 'good',
      statusLabel: '良好',
      scores: [8, 7, 7, 6, 6, 6],
      notes: [
        '官网明确记载了运营公司Cheyne Media Ltd（在直布罗陀注册，注册号122915）以及创始人Anthea Michael的履历。在本次调查的所有对象中，其披露水平也属较高。',
        '设有方针页面，明确说明依据自有的公开方法计算评分，且"评分不会因付费或合作关系而变动"。',
        '设有专页披露广告及联盟营销合作关系，并明确说明其与评分体系相互独立。',
        '披露水平较高，但由于是相对较新的网站，第三方独立核实的案例尚少。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例。',
        '在本次调查范围内未发现具体问题案例（需注意该网站较新，公开的核实案例本身就较少）。',
      ],
      sources: [
        { label: 'FX Trust Score — About Us', url: 'https://www.fxtrustscore.com/about-us/' },
        { label: 'FX Trust Score — Disclosures', url: 'https://www.fxtrustscore.com/disclosures/' },
      ],
    },
    compareforexbrokers: {
      caseNo: 'CASE No. 008',
      name: 'CompareForexBrokers',
      status: 'good',
      statusLabel: '良好',
      scores: [9, 7, 8, 6, 6, 7],
      notes: [
        '公开了创始人Justin Grossbard与Noam Korbl的真实姓名、澳大利亚墨尔本的所在地，乃至ABN注册号。在本次调查的所有对象中披露水平最高。',
        '在"Our Methodology"页面中具体说明了评价要素。',
        '在专门的"Advertiser Disclosure"页面中说明了合作费用的机制，以及"撰稿与调查团队并不知晓哪些经纪商支付了合作费用"的隔离机制。',
        '在Trustpilot上有超过37条评论，评分4/5，具有一定的口碑积累。本次调查未发现严重的真实性问题。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例。',
        '在本次调查范围内未确认存在较大的争议。',
      ],
      sources: [
        { label: 'CompareForexBrokers — About Us', url: 'https://www.compareforexbrokers.com/about-us/' },
        { label: 'CompareForexBrokers — Advertiser Disclosure', url: 'https://www.compareforexbrokers.com/about-us/advertiser-disclosure/' },
        { label: 'CompareForexBrokers — Our Methodology', url: 'https://www.compareforexbrokers.com/our-methodology/' },
      ],
    },
    forexbrokerscom: {
      caseNo: 'CASE No. 009',
      name: 'ForexBrokers.com',
      status: 'good',
      statusLabel: '良好',
      scores: [8, 7, 6, 5, 6, 6],
      notes: [
        '公开了运营方Reink Media Group, LLC（美国密歇根州，2009年成立）。该公司同时也是经第三方认证的Certified B Corporation（共益企业）。',
        '在名为"How We Calculate Forex Broker Trust"的专页中说明了信任分的计算要素。',
        'B Corp认证体现出对公共性的一定承诺，但本次调查未能确认存在详细披露广告收益的页面。',
        '在Trustpilot上可确认到一条指出"广告过多、中立性存疑"的投诉（仅1条，尚不足以构成规律性模式）。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例。',
        '在本次调查范围内未确认存在较大的争议。',
      ],
      sources: [
        { label: 'ForexBrokers.com — About Us', url: 'https://www.forexbrokers.com/about' },
        { label: 'ForexBrokers.com — How We Calculate Forex Broker Trust', url: 'https://www.forexbrokers.com/trust-score' },
        { label: 'Reink Media Group — B Corporation profile', url: 'https://www.bcorporation.net/en-us/find-a-b-corp/company/reink-media-group-llc/' },
      ],
    },
    brokerchooser: {
      caseNo: 'CASE No. 010',
      name: 'BrokerChooser',
      status: 'warn',
      statusLabel: '部分存疑',
      scores: [8, 7, 5, 4, 6, 4],
      notes: [
        '公开了创始人Tibor Bedő与Gergely Ferencz Korpos的真实姓名，以及位于匈牙利布达佩斯的所在地。',
        '在"methodology"与"why trust us"页面中说明了评价流程。',
        '设有"Advertiser Disclosure"页面，但部分批评者指出"对收益模式的说明不够充分"。',
        '在Trustpilot上可确认到多条投诉，指出"联盟营销收益与推荐排名相挂钩""在其推荐的经纪商处遭受了损失"。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例。',
        '上述Trustpilot上的投诉模式是主要案例。尚未确认存在大型媒体的调查报道。',
      ],
      sources: [
        { label: 'BrokerChooser — Advertiser Disclosure', url: 'https://brokerchooser.com/advertiser-disclosure' },
        { label: 'BrokerChooser — Online broker review methodology', url: 'https://brokerchooser.com/methodology' },
        { label: 'Trustpilot — BrokerChooser reviews', url: 'https://www.trustpilot.com/review/brokerchooser.com' },
      ],
    },
    brokersview: {
      caseNo: 'CASE No. 011',
      name: 'BrokersView',
      status: 'critical',
      statusLabel: '需警惕',
      scores: [2, 3, 2, 2, 4, 2],
      notes: [
        '官网自身也承认"办公地点未公开"。关于成立年份，不同信息来源之间也存在2017年与2022年的分歧。',
        '虽有"违规经纪商每周报告"之类的内容发布，但未能确认具体的评分计算方法。',
        '未见关于广告及收益模式的披露。',
        '有多名用户投诉称"即使付费也不删除负面评论""存在捏造的评论"。Trustpilot总体评分也仅为1.5，处于低位。',
        '本次调查未能确认与监管机构数据存在直接不一致的案例。',
        '可确认到多起用户指控，称其"收取经纪商钱款并诋毁其竞争对手"，被指存在与WikiFX类似的运作模式。',
      ],
      sources: [
        { label: 'Trustpilot — BrokersView reviews', url: 'https://www.trustpilot.com/review/www.brokersview.com' },
        { label: 'BrokersView — About Us', url: 'https://www.brokersview.com/about-us' },
        { label: 'Finance Scam — BrokersView: A Critical Review', url: 'https://www.financescam.com/2024/12/19/brokersview-a-critical-review/' },
      ],
    },
    forexbrokerrating: {
      caseNo: 'CASE No. 012',
      name: 'Forex-Broker-Rating.com',
      status: 'critical',
      statusLabel: '需警惕',
      scores: [2, 3, 2, 4, 5, 5],
      notes: [
        '官网上仅有"© 2009-2026 Forex Broker Rating.com"的版权标注，未见运营公司名称及所在地的记载。',
        '评价形式为经纪商自行注册加用户投票（根据一般行业信息了解）。未能确认具体的评分公式。',
        '未见关于广告及收益模式的披露。',
        '自行注册加投票这一形式本身在结构上存在被冒名刷票的风险，但本次调查未能确认具体的舞弊案例。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例（暂定评价）。',
        '在本次调查范围内未发现具体问题案例（需注意该网站本身信息量较少，调查的覆盖面存在局限）。',
      ],
      sources: [
        { label: 'Forex-Broker-Rating.com（俄语版）', url: 'https://www.forex-broker-rating.com/ru' },
      ],
    },
    daman: {
      caseNo: 'CASE No. 013',
      name: 'Daman（ضمان）',
      status: 'critical',
      statusLabel: '需警惕',
      scores: [2, 3, 2, 5, 5, 5],
      notes: [
        '官网上未记载运营公司名称、所在地及代表人，仅能确认一个电子邮箱地址。',
        '虽有指向相当于"评价方针"页面的链接，但未能确认其详细内容。',
        '未见关于广告及收益模式的披露。',
        '本次调查未发现能作为真实性有力依据的信息（由于网站本身信息量较少，属于暂定评价）。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例（暂定评价）。',
        '在本次调查范围内未发现具体问题案例（需注意该网站为阿拉伯语地区的小型网站，调查覆盖面存在局限）。',
      ],
      sources: [
        { label: 'Daman — 经纪商评论列表', url: 'https://daman.reviews/forex-brokers' },
      ],
    },
    seputarforex: {
      caseNo: 'CASE No. 014',
      name: 'Seputar Forex',
      status: 'warn',
      statusLabel: '部分存疑',
      scores: [4, 4, 4, 5, 6, 5],
      notes: [
        '无法直接访问官网的运营者信息页面（链接失效），因此未能确认运营公司名称及代表人。',
        '本次调查未能确认存在具体评分方法及评价逻辑的公开说明。',
        '未能确认存在关于广告及收益模式的明确披露。',
        '本次调查未发现能作为真实性有力依据的信息（由于相关信息主要为印尼语，通过英语检索的覆盖面存在局限）。',
        '该网站将经当地正规监管机构（Bappebti）注册的经纪商纳入收录对象，从与监管信息一致性的角度看，是相对积极的一点。',
        '在本次调查范围内未发现具体问题案例（需注意存在与上述相同的覆盖面局限）。',
      ],
      sources: [
        { label: 'Seputar Forex — 经纪商评论列表', url: 'https://www.seputarforex.net/broker/forex/review' },
      ],
    },
    fxscouts: {
      caseNo: 'CASE No. 015',
      name: 'FX Scouts',
      status: 'good',
      statusLabel: '良好',
      scores: [7, 6, 6, 6, 6, 6],
      notes: [
        '官网明确记载了运营方FxScouts Group AB（在瑞典注册，2011年成立）。',
        '公开了"Broker Score"与"Trust Rating"框架。在自营交易公司（Prop Firm）评价方面，也说明了验证流程。',
        '自行说明"仅依靠联盟营销收益运营，并明确披露相关关系"。',
        '发现1篇第三方文章声称其为"诈骗网站"，但由于发布方可信度较低、缺乏充分依据，因此不将其视为已确认的事实。',
        '本次调查未能确认与监管机构数据存在明确不一致的案例。',
        '除上述1篇未经核实的批评文章外，未确认存在较大的争议。',
      ],
      sources: [
        { label: 'FxScouts — About Us', url: 'https://fxscouts.com/about-us/' },
      ],
    },
  };

  const AUDIT_DATE = '2026-09-18'; // 今回の一斉調査日（再調査が発生したサイトはSITE_DATA側にhistoryを追加していく）
